// TypesFromSerializers CacheKey a19c4a3756ff3bcd3b27cb4ac49d5f39
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmailsEdit {
      id: string
      category_id?: string
      contact_id?: string
      created_at: string | Date
      email?: string
      notes?: string
      title?: string
      updated_at: string | Date
    }
  }
}
