// TypesFromSerializers CacheKey acff1654b4d47c341f55d9cd965d18dd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmailsEdit {
      id: number
      category_id?: number
      contact_id: number
      created_at: string | Date
      email?: string
      notes?: string
      title?: string
      updated_at: string | Date
    }
  }
}
