// TypesFromSerializers CacheKey fac2317ef4cb587b017274b5d7fd332f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmailsEdit {
      id: unknown
      category_id?: unknown
      contact_id?: unknown
      created_at: string | Date
      email?: string
      notes?: string
      title?: string
      updated_at: string | Date
    }
  }
}
