// TypesFromSerializers CacheKey 560f713d93ca3495f07c4782443b17e4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmailsFormData {
      id?: unknown
      category_id?: unknown
      contact_id?: unknown
      email?: string
      notes?: string
      title?: string
    }
  }
}
