// TypesFromSerializers CacheKey 125e55b6d02ae7db66296b4ef7c02423
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'

declare global {
  namespace Schema {
    interface EmailsFormData {
      id?: string
      category: Category
      category_id: string
      contact_id?: string
      email: string
      name?: string
      notes?: string
    }
  }
}
