// TypesFromSerializers CacheKey e6d09771524f79ba851d77f922d824d2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmailsFormData {
      id?: string
      category_id?: string
      contact_id?: string
      email?: string
      notes?: string
      title?: string
    }
  }
}
