// TypesFromSerializers CacheKey 9d1ed76b8d3446c987602b02f65597ba
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmailsIndex {
      id: unknown
      category_id?: unknown
      contact_id?: unknown
      created_at: string | Date
      email?: string
      notes?: string
      title?: string
      updated_at: string | Date
    }
  }
}
