// TypesFromSerializers CacheKey 0f41e23207df0a21d041110378074234
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmailsIndex {
      id: string
      category_id?: string
      contact_id?: string
      created_at: string | Date
      email?: string
      notes?: string
      title?: string
      updated_at: string | Date
    }
  }
}
