// TypesFromSerializers CacheKey b8b4b30ed6aa3f8303de1fd97af99d89
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmailsIndex {
      id: number
      category_id?: number
      contact_id: number
      created_at: string | Date
      email?: string
      notes?: string
      title?: string
      updated_at: string | Date
    }
  }
}
