// TypesFromSerializers CacheKey a1abaead1bdaf3cfd374a93e8de13ee7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmailsShow {
      id: unknown
      category_id?: unknown
      contact_id?: unknown
      created_at: string | Date
      email?: string
      notes?: string
      title?: string
      updated_at: string | Date
    }
  }
}
