// TypesFromSerializers CacheKey d66c56e90f278798f41ba12ac77b676d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'

declare global {
  namespace Schema {
    interface EmailsShow {
      id: string
      category: Category
      category_id: string
      contact_id?: string
      created_at: Date
      email: string
      name?: string
      notes?: string
      updated_at: Date
    }
  }
}
