// TypesFromSerializers CacheKey bdaa2817eaf9d6a70765d93cbb3d8114
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface SettingsFormData {
      id?: number
    }
  }
}
