// TypesFromSerializers CacheKey e915afd670f04b132b9efb75cb488618
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface SettingsPublic {
      company_name: string
    }
  }
}
