// TypesFromSerializers CacheKey 50d1b2eec9be732e4fd7a454623d3613
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DashboardStatsActivityItem {
      id: string
      created_at: string
      kind: string
      name: string
    }
  }
}
