// TypesFromSerializers CacheKey ec0df23b31bfd1f9d8e40a189c9cdb4f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DashboardStatsUpcomingEvent {
      id: string
      ends_at: string
      name: string
      starts_at: string
    }
  }
}
