// TypesFromSerializers CacheKey 37cffcb652a1d8a9f30e38e943541123
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface NonShiftEventsEdit {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
