// TypesFromSerializers CacheKey f3650f605ed34888ca4334a0637191d7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface NonShiftEventsFormData {
      id?: unknown
    }
  }
}
