// TypesFromSerializers CacheKey dd7251d05522dd9a418b228b05a72cbc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface NonShiftEventsIndex {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
