// TypesFromSerializers CacheKey 87d8a5f506ab0edbf273b482dbf61829
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type NonShiftEventsShowSchedulable from './Show/Schedulable'

declare global {
  namespace Schema {
    interface NonShiftEventsShow {
      id: unknown
      created_at: unknown
      schedulable: NonShiftEventsShowSchedulable
      updated_at: unknown
    }
  }
}
