// TypesFromSerializers CacheKey dc00e47991f5c48a4b39a2b462f3310c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CalendarRecurringPatternsFormData {
      id?: string
      day_of_month?: number
      day_of_week?: number
      end_date?: number
      max_occurrences?: number
      month_of_year?: number
      offset: number
      recurring_type: "daily" | "weekly" | "monthly" | "yearly"
      week_of_month?: number
    }
  }
}
