// TypesFromSerializers CacheKey 62b0eae00c515ff086342ad20152077f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CalendarRecurringPatternsIndex {
      id: string
      created_at: Date
      day_of_month?: number
      day_of_week?: number
      end_date?: number
      max_occurrences?: number
      month_of_year?: number
      offset: number
      recurring_type: "daily" | "weekly" | "monthly" | "yearly"
      updated_at: Date
      week_of_month?: number
    }
  }
}
