// TypesFromSerializers CacheKey 194b368afbb0a5c288fdb951011cc9a1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsEdit {
      id: unknown
      client_id: unknown
      created_at: string | Date
      doctor_id: unknown
      dosage_id: unknown
      ends_at?: string | Date
      medication_id: unknown
      start_at: unknown
      updated_at: string | Date
    }
  }
}
