// TypesFromSerializers CacheKey 70b654b0589801c063f26e39434d6554
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsEdit {
      id: number
      client_id: number
      created_at: string | Date
      doctor_id: number
      dosage_id: number
      ends_at?: string | Date
      medication_id: number
      start_at?: string | Date
      updated_at: string | Date
    }
  }
}
