// TypesFromSerializers CacheKey eddb768a175f95aa97312973c9c52744
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsEdit {
      id: unknown
      client_id: unknown
      created_at: unknown
      doctor_id: unknown
      dosage_id: unknown
      ends_at: unknown
      medication_id: unknown
      start_at: unknown
      updated_at: unknown
    }
  }
}
