// TypesFromSerializers CacheKey 76d7e4cbd9bc84ed9b98077c62ddf891
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsFormData {
      id?: string
      client_id: string
      doctor_id: string
      dosage_id: string
      ends_at?: string | Date
      medication_id: string
      start_at: unknown
    }
  }
}
