// TypesFromSerializers CacheKey 8167b87f73f982949faa04f6aac9bdb2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsFormData {
      id?: number
      client_id: number
      doctor_id: number
      dosage_id: number
      ends_at?: string | Date
      medication_id: number
      start_at?: string | Date
    }
  }
}
