// TypesFromSerializers CacheKey 9a56c7d0af65c2e9be3c4dfccd1fa005
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsFormData {
      id?: string
      client_id: string
      doctor_id: string
      dosage_id: string
      ends_at?: Date
      medication_id: string
      starts_at?: Date
    }
  }
}
