// TypesFromSerializers CacheKey a331ab65f0665aaa886ae35ade9baeee
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsIndex {
      id: unknown
      client_id: unknown
      created_at: unknown
      doctor_id: unknown
      dosage_id: unknown
      ends_at: unknown
      medication_id: unknown
      start_at: unknown
      updated_at: unknown
    }
  }
}
