// TypesFromSerializers CacheKey 10fd43e13e69202937a7129988e1f774
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsIndex {
      id: string
      client_id: string
      created_at: Date
      doctor_id: string
      dosage_id: string
      ends_at?: Date
      medication_id: string
      start_at: unknown
      updated_at: Date
    }
  }
}
