// TypesFromSerializers CacheKey 2e750a12ab707235cedc2c5a6fedc8ba
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsIndex {
      id: string
      client_id: string
      created_at: string | Date
      doctor_id: string
      dosage_id: string
      ends_at?: string | Date
      medication_id: string
      start_at: unknown
      updated_at: string | Date
    }
  }
}
