// TypesFromSerializers CacheKey 357ed0f50bcb4a6668d84dd4b0e5a836
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsShow {
      id: string
      client_id: string
      created_at: Date
      doctor_id: string
      dosage_id: string
      ends_at?: Date
      medication_id: string
      start_at: unknown
      updated_at: Date
    }
  }
}
