// TypesFromSerializers CacheKey d74a0541e9a8c3e65fbfcbac88f6579b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsShow {
      id: unknown
      client_id: unknown
      created_at: unknown
      doctor_id: unknown
      dosage_id: unknown
      ends_at: unknown
      medication_id: unknown
      start_at: unknown
      updated_at: unknown
    }
  }
}
