// TypesFromSerializers CacheKey 001a6e1cac3fd241f9480afb054c33fc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PrescriptionsShow {
      id: string
      client_id: string
      created_at: Date
      doctor_id: string
      dosage_id: string
      ends_at?: Date
      medication_id: string
      starts_at?: Date
      updated_at: Date
    }
  }
}
