// TypesFromSerializers CacheKey 8e64a9e07d2a2aa98d4f5a9a191e6394
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesEdit {
      id: string
      slug?: string
      created_at: Date
      description?: string
      title: string
      updated_at: Date
    }
  }
}
