// TypesFromSerializers CacheKey bff34964f7b495b618ada30c3f3a0747
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesEdit {
      id: string
      created_at: string | Date
      description?: string
      title: string
      updated_at: string | Date
    }
  }
}
