// TypesFromSerializers CacheKey 7ea491a55cfcfc77657f26e7d22c0234
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobtitlesEdit {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
