// TypesFromSerializers CacheKey a3e7d8f32af777fa36877b8c3bb735df
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesEdit {
      id: string
      slug?: string
      created_at: string | Date
      description?: string
      title: string
      updated_at: string | Date
    }
  }
}
