// TypesFromSerializers CacheKey d543e3291c904bd02aebcde2901461ed
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesFormData {
      id?: unknown
      description?: string
      title: string
    }
  }
}
