// TypesFromSerializers CacheKey 6dd50d1a94e4884ac3322a29b98ac683
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesFormData {
      id?: string
      description?: string
      title: string
    }
  }
}
