// TypesFromSerializers CacheKey fae62a4fde009012e958ce3cbdffdad9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobtitlesFormData {
      id?: unknown
    }
  }
}
