// TypesFromSerializers CacheKey 514c7fa95fff10f18b8ace089924a9b3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesFormData {
      id?: unknown
      slug?: unknown
      description: unknown
      name: unknown
    }
  }
}
