// TypesFromSerializers CacheKey eda83e3c2549cabf4df06bc66bb2d0de
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesIndex {
      id: string
      created_at: Date
      description?: string
      name: string
      slug: string
      updated_at: Date
    }
  }
}
