// TypesFromSerializers CacheKey 87be3c6fb2461fe6619322b4e0797648
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesIndex {
      id: string
      slug?: string
      created_at: Date
      description?: string
      name: string
      updated_at: Date
    }
  }
}
