// TypesFromSerializers CacheKey ce7f0ed38c88dd4aa164b9af46efbcfe
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesIndex {
      id: unknown
      created_at: unknown
      description: unknown
      name: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
