// TypesFromSerializers CacheKey c8c02ea0f0e806004425120625fadfaa
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesPersisted {
      id: string
      created_at: Date
      description?: string
      name: string
      slug: string
      updated_at: Date
    }
  }
}
