// TypesFromSerializers CacheKey 992f005d30447103c5b7d7fd1486cada
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesShow {
      id: string
      created_at: Date
      description?: string
      name: string
      slug: string
      updated_at: Date
    }
  }
}
