// TypesFromSerializers CacheKey 2b0aff0633d59cd7ce3d8e2a0fc152af
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesShow {
      id: unknown
      created_at: unknown
      description: unknown
      name: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
