// TypesFromSerializers CacheKey 4434b80b8384544b88a6440b36ccd5c9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobtitlesShow {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
