// TypesFromSerializers CacheKey 27a2cd325674935d7e2b6f997781b544
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitlesShow {
      id: string
      slug?: string
      created_at: Date
      description?: string
      title: string
      updated_at: Date
    }
  }
}
