// TypesFromSerializers CacheKey ce2a08ff93f344153bb65fba779dd8ec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeJobTitlesEdit {
      id: unknown
      created_at: unknown
      description: unknown
      name: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
