// TypesFromSerializers CacheKey 0c189da2efbebe283e972a3569c6ab03
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeJobTitlesFormData {
      id?: unknown
      slug?: unknown
      description: unknown
      name: unknown
    }
  }
}
