// TypesFromSerializers CacheKey 11f90e69d3ad6f20c87b8807421a49ac
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeJobTitlesIndex {
      id: unknown
      created_at: unknown
      description: unknown
      name: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
