// TypesFromSerializers CacheKey 2b6f5ffda3724543a9ce56d86dcb9b10
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeJobTitlesShow {
      id: unknown
      created_at: unknown
      description: unknown
      name: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
