// TypesFromSerializers CacheKey 1c9722d51b145d78573b00c8ef589d59
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsEdit {
      id: unknown
      category_id?: unknown
      created_at: string | Date
      name: string
      notes?: string
      updated_at: string | Date
    }
  }
}
