// TypesFromSerializers CacheKey d7afa1d73843bacc70dea5e53c7df7f9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsEdit {
      id: string
      category_id?: string
      created_at: Date
      name: string
      notes?: string
      updated_at: Date
    }
  }
}
