// TypesFromSerializers CacheKey 090895e97c3bf9412968bfc737251416
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsEdit {
      id: string
      category_id?: string
      created_at: string | Date
      name: string
      notes?: string
      updated_at: string | Date
    }
  }
}
