// TypesFromSerializers CacheKey 9a402c72f875a4b34c22d2ddc6b483b3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsFormData {
      id?: number
      category_id: number
      name?: string
      notes?: string
    }
  }
}
