// TypesFromSerializers CacheKey ee631f6a0e2750ebacc458268e32ca16
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsFormData {
      id?: string
      category_id: string
      name: string
      notes?: string
    }
  }
}
