// TypesFromSerializers CacheKey ca0f841d98eac3950b08c5f7453568dd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsFormData {
      id?: unknown
      category_id?: unknown
      name: string
      notes?: string
    }
  }
}
