// TypesFromSerializers CacheKey 832d093925e2b8b4876e6eb6bc14d32b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsIndex {
      id: string
      category_id?: string
      created_at: string | Date
      name: string
      notes?: string
      updated_at: string | Date
    }
  }
}
