// TypesFromSerializers CacheKey b7d28aabc3f39bf85817e1fc5d9c679f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsIndex {
      id: unknown
      category_id?: unknown
      created_at: string | Date
      name: string
      notes?: string
      updated_at: string | Date
    }
  }
}
