// TypesFromSerializers CacheKey 3258ef4422e327d42a28a0403577bd1b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsIndex {
      id: unknown
      category_id: unknown
      created_at: unknown
      name: unknown
      notes: unknown
      updated_at: unknown
    }
  }
}
