// TypesFromSerializers CacheKey 897a21ffaac54974fde96848fdf4fc0f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsOptions {
      id: string
      created_at: Date
      name: string
      slug: string
      updated_at: Date
    }
  }
}
