// TypesFromSerializers CacheKey 1abd123fe00f356856fe5ec5874219bc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsShow {
      id: unknown
      category_id?: unknown
      created_at: string | Date
      name?: string
      notes?: string
      updated_at: string | Date
    }
  }
}
