// TypesFromSerializers CacheKey 22b7f2e910ebb4f87afeb7527828becf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsShow {
      id: string
      category_id?: string
      created_at: Date
      name: string
      notes?: string
      updated_at: Date
    }
  }
}
