// TypesFromSerializers CacheKey c09c2567d2c989a44a60975353160a50
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsShow {
      id: unknown
      category_id: unknown
      created_at: unknown
      name: unknown
      notes: unknown
      updated_at: unknown
    }
  }
}
