// TypesFromSerializers CacheKey b5bccc9c4e7fc78fbf2b12e2f0db48ba
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CalendarRecurringPatternsEdit {
      id: unknown
      created_at: unknown
      day_of_month: unknown
      day_of_week: unknown
      end_date: unknown
      max_occurrences: unknown
      month_of_year: unknown
      offset: unknown
      recurring_type: unknown
      updated_at: unknown
      week_of_month: unknown
    }
  }
}
