// TypesFromSerializers CacheKey a0e76331260f5ec33a0a9f9c4c3e5f8f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CalendarRecurringPatternsFormData {
      id?: unknown
      day_of_month: unknown
      day_of_week: unknown
      end_date: unknown
      max_occurrences: unknown
      month_of_year: unknown
      offset: unknown
      recurring_type: unknown
      week_of_month: unknown
    }
  }
}
