// TypesFromSerializers CacheKey 7c7a03225fc3db20522fa6ca97486460
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CalendarRecurringPatternsIndex {
      id: unknown
      created_at: unknown
      day_of_month: unknown
      day_of_week: unknown
      end_date: unknown
      max_occurrences: unknown
      month_of_year: unknown
      offset: unknown
      recurring_type: unknown
      updated_at: unknown
      week_of_month: unknown
    }
  }
}
