// TypesFromSerializers CacheKey 2b978ed302bc601f15606ff45c1dfbce
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CalendarRecurringPatternsShow {
      id: unknown
      created_at: unknown
      day_of_month: unknown
      day_of_week: unknown
      end_date: unknown
      max_occurrences: unknown
      month_of_year: unknown
      offset: unknown
      recurring_type: unknown
      updated_at: unknown
      week_of_month: unknown
    }
  }
}
