// TypesFromSerializers CacheKey 301c20b8ce28ea643cdcae800417f883
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type DashboardStatsActivityItem from './Stats/ActivityItem'
import type DashboardStatsUpcomingEvent from './Stats/UpcomingEvent'

declare global {
  namespace Schema {
    interface DashboardStats {
      active_client_count: integer
      active_team_count: integer
      activity_items: DashboardStatsActivityItem[]
      hiring_pipeline_count: integer
      inactive_client_count: integer
      pending_timesheet_count: integer
      upcoming_events: DashboardStatsUpcomingEvent[]
      week_tracked_hours: number
    }
  }
}
