// TypesFromSerializers CacheKey 01e67d18830b3b2fc13983145b1b54cc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from './Category'

declare global {
  namespace Schema {
    interface Address {
      id?: unknown
      address: unknown
      address_2: unknown
      category: Category
      category_id: unknown
      city: unknown
      contact_id: unknown
      country: unknown
      name: unknown
      notes: unknown
      postal: unknown
      region: unknown
    }
  }
}
