// TypesFromSerializers CacheKey 0596b7320ff025da07a2cdf3bca95b82
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Application {
      id?: unknown
    }
  }
}
