// TypesFromSerializers CacheKey 9c2d8367ed64679a6dedb0ca8f187ec2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RecurringPattern from './RecurringPattern'

declare global {
  namespace Schema {
    interface CalendarEvent {
      id?: unknown
      created_by_id: unknown
      ends_at?: string | Date
      parent_id?: unknown
      recurring_pattern: RecurringPattern
      recurring_pattern_id?: unknown
      schedulable_id: unknown
      schedulable_type: unknown
      starts_at?: string | Date
    }
  }
}
