// TypesFromSerializers CacheKey 0091ed4bf2ecfc854ab88acc92c817f0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CalendarEvent {
      id?: number
      created_by_id: number
      ends_at?: string | Date
      parent_id?: number
      recurring_pattern_id?: number
      schedulable_id?: number
      schedulable_type?: string
      starts_at?: string | Date
    }
  }
}
