// TypesFromSerializers CacheKey 38f053418533ff896a9cd35dcb6b60a3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RecurringPattern from './RecurringPattern'

declare global {
  namespace Schema {
    interface CalendarEvent {
      id?: number
      created_by_id: number
      ends_at?: string | Date
      parent_id?: number
      recurring_pattern: RecurringPattern
      recurring_pattern_id?: number
      schedulable_id: unknown
      schedulable_type: unknown
      starts_at?: string | Date
    }
  }
}
