// TypesFromSerializers CacheKey 7069f2ab612cc3a580c921dd2613f1e1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CalendarRecurringPattern {
      id?: unknown
      day_of_month: unknown
      day_of_week: unknown
      end_date: unknown
      max_occurrences: unknown
      month_of_year: unknown
      offset: unknown
      recurring_type: unknown
      week_of_month: unknown
    }
  }
}
