// TypesFromSerializers CacheKey 9692e083e6c0b34f4b0464ffdd55a4f2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Category {
      id?: unknown
      slug?: unknown
      description: unknown
      name: unknown
    }
  }
}
