// TypesFromSerializers CacheKey 4386b5015cd49b9a808e65461d50764d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from './Person'

declare global {
  namespace Schema {
    interface Client {
      id?: number
      active_at?: string | Date
      inactive_at?: string | Date
      number?: string
      person: Person
      person_id: number
    }
  }
}
