// TypesFromSerializers CacheKey bb007c8aaaac539a5187475ea50c539c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Person } from './Person'

declare global {
  namespace Schema {
    interface Client {
      id?: number
      created_at: string | Date
      number?: number
      person: Person
      updated_at: string | Date
    }
  }
}
