// TypesFromSerializers CacheKey c9299253beab508794154dbb0c05e210
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from './Person'

declare global {
  namespace Schema {
    interface Client {
      id?: string
      active_at?: string | Date
      inactive_at?: string | Date
      number?: string
      person: Person
      person_id: string
    }
  }
}
