// TypesFromSerializers CacheKey 9c4cfc3126707bec54987633f1b33e6b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Contact {
      id?: string
      contactable_id: string
      contactable_type: string
      notes?: string
      primary_address_id?: string
      primary_email_id?: string
      primary_phone_id?: string
    }
  }
}
