// TypesFromSerializers CacheKey e9769554c105991eefad87a5b364a1a4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Contact {
      id?: unknown
      contactable_id: unknown
      contactable_type: string
      notes?: string
      primary_address_id?: unknown
      primary_email_id?: unknown
      primary_phone_id?: unknown
    }
  }
}
