// TypesFromSerializers CacheKey 8223ab4bd129fc6cf71e49f040f4bf16
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Doctor {
      id?: string
      slug?: string
      first_name: string
      last_name: string
      name: string
    }
  }
}
