// TypesFromSerializers CacheKey 8e7a2bdf0f9050ee25067306da5a26dd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Doctor {
      id?: unknown
      first_name?: string
      last_name?: string
      notes?: string
    }
  }
}
