// TypesFromSerializers CacheKey bdcd16c1e4d2769af08664c38a6c3143
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Doctor {
      id?: string
      slug?: string
      first_name: unknown
      last_name: unknown
      notes: unknown
    }
  }
}
