// TypesFromSerializers CacheKey 47293a6854ca8658b13363411db1009b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Dosage {
      id?: unknown
      amount: unknown
      amount_unit: unknown
      freq_amount: unknown
      freq_period: unknown
      notes: unknown
    }
  }
}
