// TypesFromSerializers CacheKey 40fc531f29e114bc7f02e7ed629cbb9a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Dosage {
      id?: number
      amount?: number
      amount_unit?: number
      freq_amount?: number
      freq_period?: number
      notes?: string
    }
  }
}
