// TypesFromSerializers CacheKey 2ae514d16ead7ef2cd02760fee5065cb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Dosage {
      id?: string
      amount?: string | number
      amount_unit?: number
      freq_amount?: string | number
      freq_period?: number
      notes?: string
    }
  }
}
