// TypesFromSerializers CacheKey a673d763630fcce027287f8be0840904
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Email {
      id?: string
      category_id?: string
      contact_id?: string
      email: string
      notes?: string
      title?: string
    }
  }
}
