// TypesFromSerializers CacheKey 2ffe64a10670b9f01ee095455c873a83
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Email {
      id?: number
      category_id?: number
      contact_id: number
      email?: string
      notes?: string
      title?: string
    }
  }
}
