// TypesFromSerializers CacheKey 7341fb11e03d80b3e51b34c95c726660
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from './Category'

declare global {
  namespace Schema {
    interface Email {
      id?: string
      category: Category
      category_id?: string
      contact_id?: string
      email: string
      notes?: string
      title?: string
    }
  }
}
