// TypesFromSerializers CacheKey 143ddf437a44eac3f6b39155ca5779aa
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from './JobTitle'
import type Person from './Person'

declare global {
  namespace Schema {
    interface Employee {
      id?: string
      slug?: string
      active_at?: Date
      color?: string
      color_mappings: unknown
      inactive_at?: Date
      job_title: JobTitle
      number?: string
      person: Person
      person_id: string
    }
  }
}
