// TypesFromSerializers CacheKey bdaad02b0759799b984638aeb4c59c3f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Employee {
      id?: number
      slug?: string
      first_name?: string
      job_title_id?: number
      last_name?: string
      middle_name?: string
      person_type?: number
      user_id?: number
    }
  }
}
