// TypesFromSerializers CacheKey 5916eb33670761d01ffd883d6d9a5d89
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from './JobTitle'
import type Person from './Person'

declare global {
  namespace Schema {
    interface Employee {
      id?: string
      active_at?: string | Date
      inactive_at?: string | Date
      job_title: JobTitle
      number?: string
      person: Person
      person_id: string
    }
  }
}
