// TypesFromSerializers CacheKey c2317c38815349719fc053981bb6e4b9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EventParticipant {
      id?: string
      calendar_event_id: string
      participant_id: string
      participant_type: string
    }
  }
}
