// TypesFromSerializers CacheKey ee6be4244d7e9509ab7a7b26e1973ccc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Household {
      id?: unknown
      slug?: unknown
      name: unknown
    }
  }
}
