// TypesFromSerializers CacheKey bd18be244a4fedab970cb4b4d0f5ee89
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Household {
      id?: string
      name: string
    }
  }
}
