// TypesFromSerializers CacheKey a932b4d94af9053dc8a056a04a8103c3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Household {
      id?: string
      slug?: string
      name: string
    }
  }
}
