// TypesFromSerializers CacheKey 8bb6f1fb793c89310da7c753fc960621
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Identification {
      id?: unknown
      expires_at: unknown
      extra_fields: unknown
      identificationable_id: unknown
      identificationable_type: unknown
      issued_at: unknown
      notes: unknown
      number: unknown
      type: unknown
    }
  }
}
