// TypesFromSerializers CacheKey 93e459857e37ab9de59d555a5e5cd03a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Identification {
      id?: string
      expires_at?: string | Date
      extra_fields?: Record<string, string>
      identificationable_id: string
      identificationable_type: string
      issued_at?: string | Date
      notes?: string
      number?: number
      type?: number
    }
  }
}
