// TypesFromSerializers CacheKey 3efce0a253dddf90b0f71ae28e31ec00
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Identification {
      id?: string
      expires_at?: Date
      extra_fields?: Record<string, string>
      identificationable_id: string
      identificationable_type: string
      issued_at?: Date
      notes?: string
      number?: number
      type?: number
    }
  }
}
