// TypesFromSerializers CacheKey 9ae0ed536a63a3245ab9c1e7cd219012
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentType {
      id?: number
      category_id: number
      name?: string
    }
  }
}
