// TypesFromSerializers CacheKey ed068ab01c854a926d74d23edc44732e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReport {
      id?: unknown
      agency_notified_at?: string | Date
      client_id: unknown
      description?: string
      incident_type_id: unknown
      location?: string
      occurred_at?: string | Date
      reported_at?: string | Date
      reported_by_id: unknown
      reported_to_id: unknown
    }
  }
}
