// TypesFromSerializers CacheKey c9f974cbbc8db8ce547d1237475e4cd2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentType {
      id?: unknown
      category_id?: unknown
      name?: string
    }
  }
}
