// TypesFromSerializers CacheKey c24ab55cc6bb9ef5ee6b47f47ae1199b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReport {
      id?: number
      agency_notified_at?: string | Date
      client_id: number
      description?: string
      incident_type_id: number
      location?: string
      occurred_at: unknown
      reported_at?: string | Date
      reported_by_id: number
      reported_to_id: number
    }
  }
}
