// TypesFromSerializers CacheKey 90921baaacbb2a426bb139ff2ff867f6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReport {
      id?: unknown
      agency_notified_at: unknown
      category_id: unknown
      client_id: unknown
      description: unknown
      location: unknown
      occurred_at: unknown
      reported_at: unknown
      reported_by_id: unknown
      reported_to_id: unknown
    }
  }
}
