// TypesFromSerializers CacheKey b2057f16718c6301135a466e060da760
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitle {
      id?: unknown
    }
  }
}
