// TypesFromSerializers CacheKey 301be95b4493e577156fffffd8715a1a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitle {
      id?: string
      slug?: string
      description?: string
      title: string
    }
  }
}
