// TypesFromSerializers CacheKey 7a3f284c6baa0cfcd913e5bfb87529c3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Jobtitle {
      id?: unknown
    }
  }
}
