// TypesFromSerializers CacheKey ffc3269a2c6d9371429d55e45b3fbb2f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface JobTitle {
      id?: unknown
      slug?: unknown
      description: unknown
      name: unknown
    }
  }
}
