// TypesFromSerializers CacheKey ee1003c5617a69dcb243656fe216cc4e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Medication {
      id?: number
      generic_name?: string
      name?: string
      notes?: string
    }
  }
}
