// TypesFromSerializers CacheKey 1f0eb0ad5e08a03d9fd943eb59badc1c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Medication {
      id?: unknown
      generic_name?: string
      name?: string
      notes?: string
    }
  }
}
