// TypesFromSerializers CacheKey e6c7cbdba7b65b63ded45d11e941d67f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Medication {
      id?: string
      generic_name?: string
      name: string
      notes?: string
    }
  }
}
