// TypesFromSerializers CacheKey 0dae1e6e41a5acd53c16b1dd11939df2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface NonShiftEvent {
      id?: unknown
    }
  }
}
