// TypesFromSerializers CacheKey c70bab8560f6c7d77ab35c74d2d52580
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PayPeriod {
      id: string
      approved_at?: Date
      config_snapshot?: Record<string, string>
      created_at: Date
      ends_at?: Date
      period_type?: number
      starts_at?: Date
      status?: number
      updated_at: Date
    }
  }
}
