// TypesFromSerializers CacheKey b940cdedb238675c5dfb8e3a4e11a02d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Person {
      id?: number
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      nick_name?: string
      user_id?: number
    }
  }
}
