// TypesFromSerializers CacheKey 22052b7dca702f07e9315cfe0c02b405
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Person {
      id?: number
      slug?: string
      first_name?: string
      job_title_id?: number
      last_name?: string
      middle_name?: string
      person_type?: number
      user_id?: number
    }
  }
}
