// TypesFromSerializers CacheKey 6659d3295208081a2f58a74d029f19a5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Person {
      id?: number
      first_name?: string
      full_name: string
      last_name?: string
      middle_name?: string
      nick_name?: string
      user_id?: number
    }
  }
}
