// TypesFromSerializers CacheKey ad01f3874148b3328ff3cb76f935eb13
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from './Category'

declare global {
  namespace Schema {
    interface Phone {
      id?: unknown
      category: Category
      extension: unknown
      name: unknown
      number: unknown
    }
  }
}
