// TypesFromSerializers CacheKey 62c279241dd228f8c62be8d3d0c62a63
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from './Category'

declare global {
  namespace Schema {
    interface Phone {
      id?: string
      category: Category
      extension?: string
      number: string
      title?: string
    }
  }
}
