// TypesFromSerializers CacheKey b348a67e7287b26326f219e2e758c26d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Prescription {
      id?: unknown
      client_id: unknown
      doctor_id: unknown
      dosage_id: unknown
      ends_at?: string | Date
      medication_id: unknown
      start_at?: string | Date
    }
  }
}
