// TypesFromSerializers CacheKey 5dda17fb494170315b29ee0ba5d3ede6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Prescription {
      id?: unknown
      client_id: unknown
      doctor_id: unknown
      dosage_id: unknown
      ends_at: unknown
      medication_id: unknown
      start_at: unknown
    }
  }
}
