// TypesFromSerializers CacheKey 2a546a5dd3773f5ac88f72fb9fd49092
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Prescription {
      id?: string
      client_id: string
      doctor_id: string
      dosage_id: string
      ends_at?: string | Date
      medication_id: string
      start_at: unknown
    }
  }
}
