// TypesFromSerializers CacheKey ec19390f3a5344bd7d6d0f5833cfac74
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RecurringPattern {
      id?: number
      day_of_month?: number
      day_of_week?: number
      end_date?: number
      max_occurances?: number
      month_of_year?: number
      offset: number
      recurring_type: number
      week_of_month?: number
    }
  }
}
