// TypesFromSerializers CacheKey ebbb10eceac8f02902d6c4e3399964d4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RecurringPattern {
      id?: number
      created_at: string | Date
      day_of_month?: number
      day_of_week?: number
      end_date?: number
      max_occurrences?: number
      month_of_year?: number
      offset: number
      recurring_type: number
      updated_at: string | Date
      week_of_month?: number
    }
  }
}
