// TypesFromSerializers CacheKey 9723453c85c2c66bd6b40627696a823b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Role {
      id?: unknown
      name: unknown
      resource_id: unknown
      resource_type: unknown
    }
  }
}
