// TypesFromSerializers CacheKey 5c5ffedaec2de52a04de19334596248b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Role {
      id?: unknown
      name?: string
      resource_id?: unknown
      resource_type?: string
    }
  }
}
