// TypesFromSerializers CacheKey e7e616ce9e1e6c51a3d9ea39bffc56ba
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Role {
      id?: number
      name?: string
      resource_id?: number
      resource_type?: string
    }
  }
}
