// TypesFromSerializers CacheKey 31dc8bfdaee8f26270e2357efbc81de9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Setting {
      id?: number
      company_name: unknown
      default_currency: unknown
      default_language: unknown
      default_timezone: unknown
      pay_period_type: unknown
    }
  }
}
