// TypesFromSerializers CacheKey 9f4181ab221af587b9f86266c3bbd0b4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PayrollPeriodType from '../PayrollPeriodType'

declare global {
  namespace Schema {
    interface Setting {
      company_name: string
      default_currency: string
      default_language: string
      default_timezone: string
      overtime_daily_hours: integer
      overtime_weekly_hours: integer
      payroll_period_date: string
      payroll_period_date_2: string
      payroll_period_day: string
      payroll_period_type: PayrollPeriodType
      shift_title_format: string
    }
  }
}
