// TypesFromSerializers CacheKey 326386952812865fa1edcf0b0b990ba0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Setting {
      company_name: string
      default_currency: string
      default_language: string
      default_timezone: string
      overtime_hours: integer
      pay_period_type: string
      payroll_period_type?: string
      shift_title_format: string
    }
  }
}
