// TypesFromSerializers CacheKey d41c24c870bf3ae451791d2b134f00e2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Shift {
      id?: string
      calendar_event_id: string
      employee_id: string
    }
  }
}
