// TypesFromSerializers CacheKey c90c34f0722b0a90e1097afe16ce4222
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type EmployeesPersisted from './Employees/Persisted'

declare global {
  namespace Schema {
    interface Shift {
      id?: string
      employee: EmployeesPersisted
    }
  }
}
