// TypesFromSerializers CacheKey 3af8cf68c7a5fcc9462fc94c15147a6f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type EmployeesPersisted from './Employees/Persisted'

declare global {
  namespace Schema {
    interface Shift {
      id?: string
      calendar_event_id: string
      employee: EmployeesPersisted
      employee_id: string
    }
  }
}
