// TypesFromSerializers CacheKey e70a3c8ad5e4a61264b745c5fbc884ec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Spotlight {
      id: unknown
      created_at: unknown
      type: unknown
      updated_at: unknown
    }
  }
}
