// TypesFromSerializers CacheKey 2efa0698f1314fa06ad93883ff382950
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from './Employee'

declare global {
  namespace Schema {
    interface Timesheet {
      id?: string
      approved_at?: Date
      employee: Employee
      pay_period_end: Date
      pay_period_start: Date
    }
  }
}
