// TypesFromSerializers CacheKey fb201a9e86ce41f244be6fff5c4106ea
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from './Employee'
import type PayPeriod from './PayPeriod'

declare global {
  namespace Schema {
    interface Timesheet {
      id?: string
      approved_at?: Date
      employee: Employee
      pay_period: PayPeriod
    }
  }
}
