// TypesFromSerializers CacheKey 9983e0e50dfa345ae5e96b927854f118
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Training {
      id?: string
      active_on?: Date
      description?: string
      estimated_minutes?: number
      inactive_on?: Date
      name?: string
    }
  }
}
