// TypesFromSerializers CacheKey d6a93f1791a1e1b96c60b9feeeede310
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface User {
      id?: string
      slug?: string
      active: boolean
      email: string
    }
  }
}
