// TypesFromSerializers CacheKey 19d3a541d9e35cc377717a85030b28e0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface User {
      id?: string
      active: boolean
      email: string
    }
  }
}
