// TypesFromSerializers CacheKey d4680ff8acae9f1da1030559851c7ac6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Vendor {
      id?: unknown
      category_id?: unknown
      name: string
      notes?: string
    }
  }
}
