// TypesFromSerializers CacheKey 51583ecbddd7e0ac909dd113e5f0f797
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Vendor {
      id?: unknown
      category_id?: unknown
      name?: string
      notes?: string
    }
  }
}
