// TypesFromSerializers CacheKey 1bc5b31826c1b9b9acb0cc35de29c564
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Vendor {
      id?: number
      category_id: number
      name?: string
      notes?: string
    }
  }
}
