require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/employee/interviews", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Employee::Interview. As you add validations to Employee::Interview, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Employee::Interview.create! valid_attributes
      get employee_interviews_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      interview = Employee::Interview.create! valid_attributes
      get employee_interview_url(interview)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_employee_interview_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      interview = Employee::Interview.create! valid_attributes
      get edit_employee_interview_url(interview)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Employee::Interview" do
        expect {
          post employee_interviews_url, params: { employee_interview: valid_attributes }
        }.to change(Employee::Interview, :count).by(1)
      end

      it "redirects to the created employee_interview" do
        post employee_interviews_url, params: { employee_interview: valid_attributes }
        expect(response).to redirect_to(employee_interview_url(Employee::Interview.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Employee::Interview" do
        expect {
          post employee_interviews_url, params: { employee_interview: invalid_attributes }
        }.to change(Employee::Interview, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post employee_interviews_url, params: { employee_interview: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested employee_interview" do
        interview = Employee::Interview.create! valid_attributes
        patch employee_interview_url(interview), params: { employee_interview: new_attributes }
        interview.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the employee_interview" do
        interview = Employee::Interview.create! valid_attributes
        patch employee_interview_url(interview), params: { employee_interview: new_attributes }
        interview.reload
        expect(response).to redirect_to(employee_interview_url(interview))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        interview = Employee::Interview.create! valid_attributes
        patch employee_interview_url(interview), params: { employee_interview: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested employee_interview" do
      interview = Employee::Interview.create! valid_attributes
      expect {
        delete employee_interview_url(interview)
      }.to change(Employee::Interview, :count).by(-1)
    end

    it "redirects to the employee_interviews list" do
      interview = Employee::Interview.create! valid_attributes
      delete employee_interview_url(interview)
      expect(response).to redirect_to(employee_interviews_url)
    end
  end
end
