require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/requirement/requirements", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Requirement::Requirement. As you add validations to Requirement::Requirement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Requirement::Requirement.create! valid_attributes
      get requirement_requirements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      requirement = Requirement::Requirement.create! valid_attributes
      get requirement_requirement_url(requirement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_requirement_requirement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      requirement = Requirement::Requirement.create! valid_attributes
      get edit_requirement_requirement_url(requirement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Requirement::Requirement" do
        expect {
          post requirement_requirements_url, params: { requirement_requirement: valid_attributes }
        }.to change(Requirement::Requirement, :count).by(1)
      end

      it "redirects to the created requirement_requirement" do
        post requirement_requirements_url, params: { requirement_requirement: valid_attributes }
        expect(response).to redirect_to(requirement_requirement_url(Requirement::Requirement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Requirement::Requirement" do
        expect {
          post requirement_requirements_url, params: { requirement_requirement: invalid_attributes }
        }.to change(Requirement::Requirement, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post requirement_requirements_url, params: { requirement_requirement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested requirement_requirement" do
        requirement = Requirement::Requirement.create! valid_attributes
        patch requirement_requirement_url(requirement), params: { requirement_requirement: new_attributes }
        requirement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the requirement_requirement" do
        requirement = Requirement::Requirement.create! valid_attributes
        patch requirement_requirement_url(requirement), params: { requirement_requirement: new_attributes }
        requirement.reload
        expect(response).to redirect_to(requirement_requirement_url(requirement))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        requirement = Requirement::Requirement.create! valid_attributes
        patch requirement_requirement_url(requirement), params: { requirement_requirement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested requirement_requirement" do
      requirement = Requirement::Requirement.create! valid_attributes
      expect {
        delete requirement_requirement_url(requirement)
      }.to change(Requirement::Requirement, :count).by(-1)
    end

    it "redirects to the requirement_requirements list" do
      requirement = Requirement::Requirement.create! valid_attributes
      delete requirement_requirement_url(requirement)
      expect(response).to redirect_to(requirement_requirements_url)
    end
  end
end
