// TypesFromSerializers CacheKey 92fb3802183a5024f607e92721bd7313
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from '../../Employee'

declare global {
  namespace Schema {
    interface NonShiftEventsShowSchedulable {
      id?: unknown
      employee: Employee
      employee_id: unknown
    }
  }
}
