// TypesFromSerializers CacheKey 433bc4314b24ca8577367d214ab8c43a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from '../JobTitle'
import type Person from '../Person'

declare global {
  namespace Schema {
    interface EmployeesEdit {
      id: number
      active_at?: string | Date
      created_at: string | Date
      inactive_at?: string | Date
      job_title: JobTitle
      number?: string
      person: Person
      person_id: number
      updated_at: string | Date
    }
  }
}
