// TypesFromSerializers CacheKey ce1b7008a233de4c34ee9f26e2ac1e2e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from '../JobTitle'
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface EmployeesEdit {
      id: string
      active_at?: Date
      created_at: Date
      inactive_at?: Date
      job_title: JobTitle
      number?: string
      person: PeoplePersisted
      person_id: string
      slug: string
      updated_at: Date
    }
  }
}
