// TypesFromSerializers CacheKey 0088368b1b7c20cd3f2021bfa4f6d39d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeesEdit {
      id: number
      created_at: string | Date
      first_name?: string
      job_title_id?: number
      last_name?: string
      middle_name?: string
      person_type?: number
      slug: string
      updated_at: string | Date
      user_id?: number
    }
  }
}
