// TypesFromSerializers CacheKey 0c8124db720fbd3753eaa4dc47fe3864
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from '../JobTitle'
import type Person from '../Person'

declare global {
  namespace Schema {
    interface EmployeesFormData {
      id?: string
      slug?: string
      active_at?: string | Date
      inactive_at?: string | Date
      job_title: JobTitle
      number?: string
      person: Person
      person_id: string
    }
  }
}
