// TypesFromSerializers CacheKey 05fe0bf6a2e4b4aa0edf38aba30070bb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type EmployeeJobTitle from '../Employee/JobTitle'
import type Person from '../Person'

declare global {
  namespace Schema {
    interface EmployeesFormData {
      id?: string
      slug?: string
      active_at?: Date
      color?: string
      color_mappings: Record<string, Record<string, string>>
      first_name: string
      full_name: string
      inactive_at?: Date
      job_title: EmployeeJobTitle
      last_name: string
      name: string
      number?: string
      person: Person
      person_id: string
      status: "applicant" | "offered" | "employed" | "declined" | "terminated"
    }
  }
}
