// TypesFromSerializers CacheKey b82c32048dcc8c8008ff5283dfcda506
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from '../JobTitle'
import type Person from '../Person'

declare global {
  namespace Schema {
    interface EmployeesFormData {
      id?: unknown
      slug?: unknown
      active_at: unknown
      color: unknown
      color_mappings: unknown
      inactive_at: unknown
      job_title: JobTitle
      number: unknown
      person: Person
      person_id: unknown
    }
  }
}
