// TypesFromSerializers CacheKey 0217a27c82a751ce019e037c18839b8e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type EmployeeJobTitle from '../Employee/JobTitle'
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface EmployeesIndex {
      id: string
      active_at?: Date
      color?: string
      color_mappings: Record<string, Record<string, string>>
      created_at: Date
      first_name: string
      full_name: string
      inactive_at?: Date
      job_title: EmployeeJobTitle
      last_name: string
      name: string
      number?: string
      person: PeoplePersisted
      person_id: string
      slug: string
      status: "applicant" | "offered" | "employed" | "declined" | "terminated"
      updated_at: Date
    }
  }
}
