// TypesFromSerializers CacheKey ee1f2bd846561100e269ad851291fb8b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from '../JobTitle'
import type Person from '../Person'

declare global {
  namespace Schema {
    interface EmployeesIndex {
      id: string
      slug?: string
      active_at?: string | Date
      created_at: string | Date
      inactive_at?: string | Date
      job_title: JobTitle
      number?: string
      person: Person
      person_id: string
      updated_at: string | Date
    }
  }
}
