// TypesFromSerializers CacheKey d5e9d0aac55fe217816fd42ddb889af1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { EmployeeSettings } from '../../EmployeeSettings'
import type { Person } from '../Person'

declare global {
  namespace Schema {
    interface EmployeesIndex {
      id: number
      created_at: string | Date
      number?: number
      person: Person
      settings: EmployeeSettings
      updated_at: string | Date
    }
  }
}
