// TypesFromSerializers CacheKey 8782e0e7082d47e5c4cbeb337650de8c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from '../JobTitle'
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface EmployeesOptions {
      id: string
      active_at?: Date
      color?: string
      color_mappings: unknown
      created_at: Date
      inactive_at?: Date
      job_title: JobTitle
      number?: string
      person: PeoplePersisted
      person_id: string
      slug: string
      updated_at: Date
    }
  }
}
