// TypesFromSerializers CacheKey 574bb459aad17f3b9874cbe9f777aed8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface EmployeesOptions {
      id: string
      active_at?: Date
      color_mappings: Record<string, Record<string, string>>
      created_at: Date
      first_name: string
      full_name: string
      inactive_at?: Date
      last_name: string
      name: string
      number?: string
      person: Person
      slug: string
      updated_at: Date
    }
  }
}
