// TypesFromSerializers CacheKey 99bc81be41076704e891f265397845a6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from '../JobTitle'
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface EmployeesOptions {
      id: unknown
      active_at: unknown
      color: unknown
      color_mappings: unknown
      created_at: unknown
      inactive_at: unknown
      job_title: JobTitle
      number: unknown
      person: PeoplePersisted
      person_id: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
