// TypesFromSerializers CacheKey 44d7393bec4dbca3f5a4ec7984fccf92
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type EmployeeJobTitle from '../Employee/JobTitle'
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface EmployeesPersisted {
      id: string
      active_at?: Date
      color?: string
      color_mappings: Record<string, Record<string, string>>
      created_at: Date
      first_name: string
      full_name: string
      inactive_at?: Date
      job_title: EmployeeJobTitle
      last_name: string
      name: string
      number?: string
      person: PeoplePersisted
      person_id: string
      slug: string
      updated_at: Date
    }
  }
}
