// TypesFromSerializers CacheKey 78ac2f20441dbcc858669ec016a3e51e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeesShallow {
      id?: number
      created_at: string | Date
      number?: number
      settings: Record<string, string>
      updated_at: string | Date
    }
  }
}
