// TypesFromSerializers CacheKey 0cba8b122ac9ef6745bba47118a66542
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { EmployeeSettings } from '../../EmployeeSettings'

declare global {
  namespace Schema {
    interface EmployeesShallow {
      id?: number
      created_at: string | Date
      number?: number
      settings: EmployeeSettings
      updated_at: string | Date
    }
  }
}
