// TypesFromSerializers CacheKey ea5e65fc6b0580578779fe0bc60806b8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from '../JobTitle'
import type Person from '../Person'

declare global {
  namespace Schema {
    interface EmployeesShow {
      id: unknown
      active_at?: string | Date
      created_at: string | Date
      inactive_at?: string | Date
      job_title: JobTitle
      number?: string
      person: Person
      person_id: unknown
      updated_at: string | Date
    }
  }
}
