// TypesFromSerializers CacheKey 5f2c87aca1c344816b8a69e6b4592b9c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type JobTitle from '../JobTitle'
import type Person from '../Person'

declare global {
  namespace Schema {
    interface EmployeesShow {
      id: string
      active_at?: string | Date
      created_at: string | Date
      inactive_at?: string | Date
      job_title: JobTitle
      number?: string
      person: Person
      person_id: string
      updated_at: string | Date
    }
  }
}
