// TypesFromSerializers CacheKey 71b0a6a002be55bd2b7f2e3dc7d30dd0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeesSpotlight {
      id: string
      created_at: Date
      first_name: string
      full_name: string
      last_name: string
      name: string
      slug: string
      type: unknown
      updated_at: Date
    }
  }
}
