// TypesFromSerializers CacheKey a03c8bfa14de4fb9435f344f3fb0cc1a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from '../Employee'
import type PayPeriod from '../PayPeriod'

declare global {
  namespace Schema {
    interface TimesheetsEdit {
      id: string
      approved_at?: Date
      created_at: Date
      employee: Employee
      pay_period: PayPeriod
      updated_at: Date
    }
  }
}
