// TypesFromSerializers CacheKey a77f16d5bbc30c90c57f8172e84d0a62
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from '../Employee'

declare global {
  namespace Schema {
    interface TimesheetsEdit {
      id: string
      approved_at?: Date
      created_at: Date
      employee: Employee
      pay_period_end: Date
      pay_period_start: Date
      updated_at: Date
    }
  }
}
