// TypesFromSerializers CacheKey 3b903ca24576bf599f81e054aded729c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from '../Employee'
import type PayPeriod from '../PayPeriod'

declare global {
  namespace Schema {
    interface TimesheetsFormData {
      id?: string
      approved_at?: Date
      employee: Employee
      pay_period: PayPeriod
    }
  }
}
