// TypesFromSerializers CacheKey af0954d908f84dcac2254613c514a990
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from '../Employee'

declare global {
  namespace Schema {
    interface TimesheetsFormData {
      id?: string
      approved_at?: Date
      employee: Employee
      pay_period_end: Date
      pay_period_start: Date
    }
  }
}
