// TypesFromSerializers CacheKey 382c04f045f88d24d71089f74ceb783b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from '../Employee'
import type PayPeriod from '../PayPeriod'

declare global {
  namespace Schema {
    interface TimesheetsIndex {
      id: string
      approved_at?: Date
      created_at: Date
      employee: Employee
      pay_period: PayPeriod
      updated_at: Date
    }
  }
}
