// TypesFromSerializers CacheKey 93d29e602b981dc1e965a90f05d7fb39
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from '../Employee'

declare global {
  namespace Schema {
    interface TimesheetsIndex {
      id: string
      approved_at?: Date
      created_at: Date
      employee: Employee
      pay_period_end: Date
      pay_period_start: Date
      updated_at: Date
    }
  }
}
