// TypesFromSerializers CacheKey a131ef5afc8758a50e02f9d07d7f9f60
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from '../Employee'
import type PayPeriod from '../PayPeriod'

declare global {
  namespace Schema {
    interface TimesheetsPersisted {
      id: string
      approved_at?: Date
      created_at: Date
      employee: Employee
      pay_period: PayPeriod
      updated_at: Date
    }
  }
}
