// TypesFromSerializers CacheKey 76942391f66cbb5b8fe3afbf4994b291
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from '../Employee'

declare global {
  namespace Schema {
    interface TimesheetsShow {
      id: string
      approved_at?: Date
      created_at: Date
      employee: Employee
      pay_period_end: Date
      pay_period_start: Date
      updated_at: Date
    }
  }
}
