// TypesFromSerializers CacheKey e205f48cd74542d2d2fa9bc7dd81c2b5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Employee from '../Employee'
import type PayPeriod from '../PayPeriod'

declare global {
  namespace Schema {
    interface TimesheetsShow {
      id: string
      approved_at?: Date
      created_at: Date
      employee: Employee
      pay_period: PayPeriod
      updated_at: Date
    }
  }
}
