// TypesFromSerializers CacheKey 4f0d65fab7e31a9cd9d50c9eefb70cb1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeInterviewsEdit {
      id: unknown
      created_at: unknown
      employee_id: unknown
      notes: unknown
      scheduled_at: unknown
      updated_at: unknown
    }
  }
}
