// TypesFromSerializers CacheKey 8aa02ecebe4c869d736f2b7c070665bf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeInterviewsFormData {
      id?: unknown
      employee_id: unknown
      notes: unknown
      scheduled_at: unknown
    }
  }
}
