// TypesFromSerializers CacheKey 87d0602609004339e0f221e55efd8ca3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeInterviewsIndex {
      id: unknown
      created_at: unknown
      employee_id: unknown
      notes: unknown
      scheduled_at: unknown
      updated_at: unknown
    }
  }
}
