// TypesFromSerializers CacheKey bb056164aa0df30bec7a3c3c0afc1e8d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeInterviewsPersisted {
      id: unknown
      created_at: unknown
      employee_id: unknown
      notes: unknown
      scheduled_at: unknown
      updated_at: unknown
    }
  }
}
