// TypesFromSerializers CacheKey cec9dffad14d16b6bf0eb5d49f6a35fd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeInterviewsShow {
      id: unknown
      created_at: unknown
      employee_id: unknown
      notes: unknown
      scheduled_at: unknown
      updated_at: unknown
    }
  }
}
