// TypesFromSerializers CacheKey 760f9a36cf580388e9b7d9076eb3b0e3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RecurringPatternsEdit {
      id: number
      created_at: string | Date
      day_of_month?: number
      day_of_week?: number
      end_date?: number
      max_occurances?: number
      month_of_year?: number
      offset: number
      recurring_type: number
      updated_at: string | Date
      week_of_month?: number
    }
  }
}
