// TypesFromSerializers CacheKey 8c8d6f26b0c8aab9b34aabfed3d80fd4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RecurringPatternsFormData {
      id?: number
      day_of_month?: number
      day_of_week?: number
      end_date?: number
      max_occurrences?: number
      month_of_year?: number
      offset: number
      recurring_type: number
      week_of_month?: number
    }
  }
}
