// TypesFromSerializers CacheKey fcc2ec23107b8c479374864f903544e5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RecurringPatternsFormData {
      id?: number
      day_of_month?: number
      day_of_week?: number
      end_date?: number
      max_occurances?: number
      month_of_year?: number
      offset: number
      recurring_type: number
      week_of_month?: number
    }
  }
}
