require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/employees_job_titles" do

  # This should return the minimal set of attributes required to create a valid
  # EmployeesJobTitle. As you add validations to EmployeesJobTitle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EmployeesJobTitle.create! valid_attributes
      get employees_job_titles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      employees_job_title = EmployeesJobTitle.create! valid_attributes
      get employees_job_title_url(employees_job_title)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_employees_job_title_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      employees_job_title = EmployeesJobTitle.create! valid_attributes
      get edit_employees_job_title_url(employees_job_title)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EmployeesJobTitle" do
        expect {
          post employees_job_titles_url, params: { employees_job_title: valid_attributes }
        }.to change(EmployeesJobTitle, :count).by(1)
      end

      it "redirects to the created employees_job_title" do
        post employees_job_titles_url, params: { employees_job_title: valid_attributes }
        expect(response).to redirect_to(employees_job_title_url(EmployeesJobTitle.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EmployeesJobTitle" do
        expect {
          post employees_job_titles_url, params: { employees_job_title: invalid_attributes }
        }.not_to change(EmployeesJobTitle, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post employees_job_titles_url, params: { employees_job_title: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested employees_job_title" do
        employees_job_title = EmployeesJobTitle.create! valid_attributes
        patch employees_job_title_url(employees_job_title), params: { employees_job_title: new_attributes }
        employees_job_title.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the employees_job_title" do
        employees_job_title = EmployeesJobTitle.create! valid_attributes
        patch employees_job_title_url(employees_job_title), params: { employees_job_title: new_attributes }
        employees_job_title.reload
        expect(response).to redirect_to(employees_job_title_url(employees_job_title))
      end
    end

    context "with invalid parameters" do

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        employees_job_title = EmployeesJobTitle.create! valid_attributes
        patch employees_job_title_url(employees_job_title), params: { employees_job_title: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested employees_job_title" do
      employees_job_title = EmployeesJobTitle.create! valid_attributes
      expect {
        delete employees_job_title_url(employees_job_title)
      }.to change(EmployeesJobTitle, :count).by(-1)
    end

    it "redirects to the employees_job_titles list" do
      employees_job_title = EmployeesJobTitle.create! valid_attributes
      delete employees_job_title_url(employees_job_title)
      expect(response).to redirect_to(employees_job_titles_url)
    end
  end
end
