require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/incident_reports", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # IncidentReport. As you add validations to IncidentReport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      IncidentReport.create! valid_attributes
      get incident_reports_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      incident_report = IncidentReport.create! valid_attributes
      get incident_report_url(incident_report)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_incident_report_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      incident_report = IncidentReport.create! valid_attributes
      get edit_incident_report_url(incident_report)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new IncidentReport" do
        expect {
          post incident_reports_url, params: { incident_report: valid_attributes }
        }.to change(IncidentReport, :count).by(1)
      end

      it "redirects to the created incident_report" do
        post incident_reports_url, params: { incident_report: valid_attributes }
        expect(response).to redirect_to(incident_report_url(IncidentReport.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new IncidentReport" do
        expect {
          post incident_reports_url, params: { incident_report: invalid_attributes }
        }.to change(IncidentReport, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post incident_reports_url, params: { incident_report: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested incident_report" do
        incident_report = IncidentReport.create! valid_attributes
        patch incident_report_url(incident_report), params: { incident_report: new_attributes }
        incident_report.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the incident_report" do
        incident_report = IncidentReport.create! valid_attributes
        patch incident_report_url(incident_report), params: { incident_report: new_attributes }
        incident_report.reload
        expect(response).to redirect_to(incident_report_url(incident_report))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        incident_report = IncidentReport.create! valid_attributes
        patch incident_report_url(incident_report), params: { incident_report: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested incident_report" do
      incident_report = IncidentReport.create! valid_attributes
      expect {
        delete incident_report_url(incident_report)
      }.to change(IncidentReport, :count).by(-1)
    end

    it "redirects to the incident_reports list" do
      incident_report = IncidentReport.create! valid_attributes
      delete incident_report_url(incident_report)
      expect(response).to redirect_to(incident_reports_url)
    end
  end
end
