/* eslint no-unused-vars: 0 */

/**
 * auto-generated file
 * schema version: 20220130172147
 * This file was automatically generated by schema2type
 */
declare namespace schema {
  type Address = {
    id: number;
    title: string | null;
    address: string | null;
    address_2: string | null;
    city: string | null;
    region: string | null;
    country: string | null;
    postal: string | null;
    notes: string | null;
    contact_id: number;
    created_at: string;
    updated_at: string;
  }

  type Contact = {
    id: number;
    contactable_type: string;
    contactable_id: number;
    created_at: string;
    updated_at: string;
    primary_address_id: number | null;
    primary_phone_id: number | null;
    primary_email_id: number | null;
  }

  type Email = {
    id: number;
    title: string | null;
    email: string | null;
    notes: string | null;
    contact_id: number;
    created_at: string;
    updated_at: string;
  }

  type Person = {
    id: number;
    f_name: string | null;
    m_name: string | null;
    l_name: string | null;
    slug: string;
    person_type: number | null;
    user_id: number | null;
    created_at: string;
    updated_at: string;
  }

  type PeopleShift = {
    id: number;
    shift_id: number;
    person_id: number;
  }

  type Phone = {
    id: number;
    title: string | null;
    number: string | null;
    extension: string | null;
    notes: string | null;
    contact_id: number;
    created_at: string;
    updated_at: string;
  }

  type RecurringPattern = {
    id: number;
    shift_id: number;
    recurring_type: number | null;
    separation_count: number | null;
    max_occurances: number | null;
    day_of_week: number | null;
    week_of_month: number | null;
    day_of_month: number | null;
    month_of_year: number | null;
    created_at: string;
    updated_at: string;
  }

  type ShiftException = {
    id: number;
    shift_id: number;
    rescheduled: string | null;
    cancelled: string | null;
    starts_at: string | null;
    ends_at: string | null;
    created_at: string;
    updated_at: string;
  }

  type Shift = {
    id: number;
    starts_at: string | null;
    ends_at: string | null;
    is_recurring: boolean | null;
    employee_id: number | null;
    created_by_id: number;
    parent_id: number | null;
    created_at: string;
    updated_at: string;
  }

  type User = {
    id: number;
    email: string;
    encrypted_password: string;
    reset_password_token: string | null;
    reset_password_sent_at: string | null;
    remember_created_at: string | null;
    sign_in_count: number;
    current_sign_in_at: string | null;
    last_sign_in_at: string | null;
    current_sign_in_ip: string | null;
    last_sign_in_ip: string | null;
    confirmation_token: string | null;
    confirmed_at: string | null;
    confirmation_sent_at: string | null;
    unconfirmed_email: string | null;
    failed_attempts: number;
    unlock_token: string | null;
    locked_at: string | null;
    created_at: string;
    updated_at: string;
    active: boolean | null;
    time_zone: string | null;
  }
}
