// TypesFromSerializers CacheKey aa43fb9219b8c47b15657cafccbe0c05
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DosagesEdit {
      id: unknown
      amount?: string | number
      amount_unit?: number
      created_at: string | Date
      freq_amount?: string | number
      freq_period?: number
      notes?: string
      updated_at: string | Date
    }
  }
}
