// TypesFromSerializers CacheKey 3a75718550387a5d57c8b318348d192f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DosagesEdit {
      id: unknown
      amount: unknown
      amount_unit: unknown
      created_at: unknown
      freq_amount: unknown
      freq_period: unknown
      notes: unknown
      updated_at: unknown
    }
  }
}
