// TypesFromSerializers CacheKey f7f6cbacaa0e6518648c28dbd4c48e2e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DosagesEdit {
      id: string
      amount?: string | number
      amount_unit?: number
      created_at: string | Date
      freq_amount?: string | number
      freq_period?: number
      notes?: string
      updated_at: string | Date
    }
  }
}
