// TypesFromSerializers CacheKey 49d8411e9dfe79c75e274e51feb586c4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DosagesFormData {
      id?: unknown
      amount?: string | number
      amount_unit?: number
      freq_amount?: string | number
      freq_period?: number
      notes?: string
    }
  }
}
