// TypesFromSerializers CacheKey f5d100f12e522658ca32aaa3360da165
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DosagesIndex {
      id: string
      amount?: string | number
      amount_unit?: number
      created_at: Date
      freq_amount?: string | number
      freq_period?: number
      notes?: string
      updated_at: Date
    }
  }
}
