// TypesFromSerializers CacheKey 59c0a46a92559d2239541fd6178b0374
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DosagesIndex {
      id: number
      amount?: number
      amount_unit?: number
      created_at: string | Date
      freq_amount?: number
      freq_period?: number
      notes?: string
      updated_at: string | Date
    }
  }
}
