// TypesFromSerializers CacheKey aa47afd3ede6ef0d9f4bc0137ebfcff7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DosagesIndex {
      id: unknown
      amount?: string | number
      amount_unit?: number
      created_at: string | Date
      freq_amount?: string | number
      freq_period?: number
      notes?: string
      updated_at: string | Date
    }
  }
}
