// TypesFromSerializers CacheKey fd228425eadd3783225cc45d445fc83c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DosagesShow {
      id: unknown
      amount: unknown
      amount_unit: unknown
      created_at: unknown
      freq_amount: unknown
      freq_period: unknown
      notes: unknown
      updated_at: unknown
    }
  }
}
