// TypesFromSerializers CacheKey 59ab03a978832187d927e585ec3b5bc7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DosagesShow {
      id: number
      amount?: number
      amount_unit?: number
      created_at: string | Date
      freq_amount?: number
      freq_period?: number
      notes?: string
      updated_at: string | Date
    }
  }
}
