// TypesFromSerializers CacheKey b08a644c05751f6e7392f769d7e36e98
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DosagesShow {
      id: string
      amount?: string | number
      amount_unit?: number
      created_at: Date
      freq_amount?: string | number
      freq_period?: number
      notes?: string
      updated_at: Date
    }
  }
}
