// TypesFromSerializers CacheKey 8bb1a1d9dc08b2627b36ed4cda2d140e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftTemplatesEdit {
      id: string
      active: boolean
      client_id: string
      created_at: Date
      created_by_id?: string
      end_date?: Date
      frequency: "weekly" | "biweekly" | "monthly"
      name?: string
      start_date?: Date
      updated_at: Date
    }
  }
}
