// TypesFromSerializers CacheKey 114d03376ccd35ca669f2c13f59c8da1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftTemplatesFormData {
      id?: string
      active: boolean
      client_id: string
      created_by_id?: string
      end_date?: Date
      frequency: "weekly" | "biweekly" | "monthly"
      name?: string
      start_date?: Date
    }
  }
}
