// TypesFromSerializers CacheKey e36d1f58c67c52c8687916d9455826de
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftTemplatesPersisted {
      id: string
      active: boolean
      client_id: string
      created_at: Date
      created_by_id?: string
      end_date?: Date
      frequency: "weekly" | "biweekly" | "monthly"
      name?: string
      start_date?: Date
      updated_at: Date
    }
  }
}
