// TypesFromSerializers CacheKey 2657515cbe2de3050106086c7bd17541
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftTemplatesShow {
      id: string
      active: boolean
      client_id: string
      created_at: Date
      created_by_id?: string
      end_date?: Date
      frequency: "weekly" | "biweekly" | "monthly"
      name?: string
      start_date?: Date
      updated_at: Date
    }
  }
}
