// TypesFromSerializers CacheKey f541e71b9c27455b06a1cca15bde5e05
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'
import type EmployeesPersisted from '../Employees/Persisted'

declare global {
  namespace Schema {
    interface ShiftsClient {
      id?: string
      calendar_event_id: string
      category: Category
      employee: EmployeesPersisted
      employee_id: string
    }
  }
}
