// TypesFromSerializers CacheKey e5b3043eb2db5a4a593c3abf05833212
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftsEdit {
      id: number
      created_at: string | Date
      created_by_id: unknown
      employee_id?: number
      ends_at: unknown
      parent_id: unknown
      recurring_pattern_id: unknown
      starts_at: unknown
      title: string
      updated_at: string | Date
    }
  }
}
