// TypesFromSerializers CacheKey 0daa098937ae3495e0e7fa9d8f6ed7c7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftsEdit {
      id: number
      created_at: string | Date
      created_by_id: number
      employee_id?: number
      ends_at?: string | Date
      parent_id?: number
      recurring_pattern_id?: number
      starts_at?: string | Date
      title: unknown
      updated_at: string | Date
    }
  }
}
