// TypesFromSerializers CacheKey 8bb765868ccea62864aaed6ca5cf1f31
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'
import type EmployeesPersisted from '../Employees/Persisted'

declare global {
  namespace Schema {
    interface ShiftsEmployee {
      id?: string
      calendar_event_id: string
      category: Category
      employee: EmployeesPersisted
      employee_id: string
    }
  }
}
