// TypesFromSerializers CacheKey 5c275c0750e18e0691d0d70e085da3d7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftsEmployee {
      id?: string
      calendar_event_id: string
      employee_id: string
    }
  }
}
