// TypesFromSerializers CacheKey 8ca3959a833ef137565e83c4bed32bda
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type EmployeesPersisted from '../Employees/Persisted'

declare global {
  namespace Schema {
    interface ShiftsEmployee {
      id?: string
      calendar_event_id: string
      employee: EmployeesPersisted
      employee_id: string
    }
  }
}
