// TypesFromSerializers CacheKey 4a37653063ae79a1033b841b3c3ee121
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftsFormData {
      id?: number
      client_id?: number
      created_by_id: unknown
      employee_id?: number
      ends_at: unknown
      parent_id: unknown
      recurring_pattern_id: unknown
      starts_at: unknown
      title: string
    }
  }
}
