// TypesFromSerializers CacheKey 13ef5520b1a696d6d30f2f712e5d42c4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Client from '../Client'
import type Employee from '../Employee'
import type Household from '../Household'

declare global {
  namespace Schema {
    interface ShiftsFormData {
      id?: number
      clients: Client[]
      employee: Employee
      employee_id: number
      households: Household[]
    }
  }
}
