// TypesFromSerializers CacheKey 8b9f3a35b45644af620e16edcbab496b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftsFormData {
      id?: number
      created_by_id: number
      employee_id?: number
      ends_at?: string | Date
      parent_id?: number
      recurring_pattern_id?: number
      starts_at?: string | Date
      title: string
    }
  }
}
