// TypesFromSerializers CacheKey 17a6c29ea7c7e9d73113441772618a87
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftsIndex {
      id: number
      client_id?: number
      created_at: string | Date
      created_by_id: unknown
      employee_id?: number
      ends_at: unknown
      parent_id: unknown
      recurring_pattern_id: unknown
      starts_at: unknown
      title: string
      updated_at: string | Date
    }
  }
}
