// TypesFromSerializers CacheKey 88372c8eff1306fecbf2ed0dc0051021
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Client from '../Client'
import type Employee from '../Employee'
import type Household from '../Household'

declare global {
  namespace Schema {
    interface ShiftsIndex {
      id: number
      clients: Client[]
      created_at: string | Date
      employee: Employee
      employee_id: number
      households: Household[]
      updated_at: string | Date
    }
  }
}
