// TypesFromSerializers CacheKey 612c3baf16abc26aa3137cda67870985
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftsIndex {
      id: number
      created_at: string | Date
      created_by_id: number
      employee_id?: number
      ends_at?: string | Date
      parent_id?: number
      recurring_pattern_id?: number
      starts_at?: string | Date
      title: string
      updated_at: string | Date
    }
  }
}
