// TypesFromSerializers CacheKey 18e514e288444bcef5052b9dd0fc9b33
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'

declare global {
  namespace Schema {
    interface ShiftsReview {
      id: string
      calendar_event_id: string
      category: Category
      created_at: Date
      employee_id: string
      ends_at: unknown
      starts_at: unknown
      updated_at: Date
    }
  }
}
