// TypesFromSerializers CacheKey 1cb27448c283bcbe01c695460c1725a7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'

declare global {
  namespace Schema {
    interface ShiftsReview {
      id: string
      calendar_event_id: string
      category: Category
      client_name: string
      created_at: Date
      employee_id: string
      ends_at: Date
      starts_at: Date
      updated_at: Date
    }
  }
}
