// TypesFromSerializers CacheKey 2df9a8d755eaaa6851683aaff12d5243
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftsShallow {
      id?: number
      created_at: string | Date
      employee_id?: number
      ends_at?: string | Date
      starts_at?: string | Date
      title?: string
      updated_at: string | Date
    }
  }
}
