// TypesFromSerializers CacheKey e3a8beefa6046260fbf3fa8af9e95163
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Client from '../Client'
import type Employee from '../Employee'
import type Household from '../Household'

declare global {
  namespace Schema {
    interface ShiftsShow {
      id: number
      clients: Client[]
      created_at: string | Date
      employee: Employee
      employee_id: number
      households: Household[]
      updated_at: string | Date
    }
  }
}
