// TypesFromSerializers CacheKey 26780a896b4efc3438085938a547ba28
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ShiftsShow {
      id: number
      client_id?: number
      created_at: string | Date
      created_by_id: unknown
      employee_id?: number
      ends_at: unknown
      parent_id: unknown
      recurring_pattern_id: unknown
      starts_at: unknown
      title: string
      updated_at: string | Date
    }
  }
}
