// TypesFromSerializers CacheKey 4d86c5bd79c5f4d6ca1d120f80426cfc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarEvent from '../CalendarEvent'
import type Client from '../Client'
import type Employee from '../Employee'
import type Household from '../Household'

declare global {
  namespace Schema {
    interface ShiftsShow {
      id: unknown
      calendar_event: CalendarEvent
      clients: Client[]
      created_at: unknown
      employee: Employee
      employee_id: unknown
      households: Household[]
      updated_at: unknown
    }
  }
}
