// TypesFromSerializers CacheKey 29edf20370698a8685840ae1e1be0306
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface ClientsEdit {
      id: number
      active_at?: string | Date
      created_at: string | Date
      inactive_at?: string | Date
      number?: string
      person: Person
      person_id: number
      updated_at: string | Date
    }
  }
}
