// TypesFromSerializers CacheKey 18743303c9682b6b5ba8f42c342b7e7b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface ClientsEdit {
      id: string
      active_at?: string | Date
      created_at: string | Date
      inactive_at?: string | Date
      number?: string
      person: PeoplePersisted
      person_id: string
      slug: string
      updated_at: string | Date
    }
  }
}
