// TypesFromSerializers CacheKey 23163a8f0b6f8cb5e691d53d5e17d32c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ClientsFormData {
      id?: number
      slug?: string
      first_name?: string
      job_title_id?: number
      last_name?: string
      middle_name?: string
      person_type?: number
      user_id?: number
    }
  }
}
