// TypesFromSerializers CacheKey 48dec4fd832e2402d2bb9e69f9911c3d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface ClientsFormData {
      id?: string
      active_at?: string | Date
      inactive_at?: string | Date
      number?: string
      person: Person
      person_id: string
    }
  }
}
