// TypesFromSerializers CacheKey 187dfd2ad588f29978876a32b3ac07c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface ClientsFormData {
      id?: string
      slug?: string
      active_at?: string | Date
      inactive_at?: string | Date
      number?: string
      person: Person
      person_id: string
    }
  }
}
