// TypesFromSerializers CacheKey 63fe5bd9509eb404f49efd808c02231f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ClientsIndex {
      id: number
      created_at: string | Date
      first_name?: string
      job_title_id?: number
      last_name?: string
      middle_name?: string
      person_type?: number
      slug: string
      updated_at: string | Date
      user_id?: number
    }
  }
}
