// TypesFromSerializers CacheKey 0d2e3b48a6cd8e0cce9e3262ba9beca9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type HouseholdsPersisted from '../Households/Persisted'
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface ClientsIndex {
      id: string
      active_at?: Date
      color?: string
      color_mappings: Record<string, Record<string, string>>
      created_at: Date
      first_name: string
      full_name: string
      household: HouseholdsPersisted
      inactive_at?: Date
      last_name: string
      name: string
      number?: string
      person: PeoplePersisted
      person_id: string
      slug: string
      updated_at: Date
    }
  }
}
