// TypesFromSerializers CacheKey 33be16a2dbf06ec06ae94d2a562542b1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface ClientsIndex {
      id: number
      active_at?: string | Date
      created_at: string | Date
      inactive_at?: string | Date
      number?: string
      person: Person
      person_id: number
      updated_at: string | Date
    }
  }
}
