// TypesFromSerializers CacheKey f188547a75fde6aa146544cd8efa5b62
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ClientsOptions {
      id: string
      active_at?: Date
      color?: string
      color_mappings: Record<string, Record<string, string>>
      created_at: Date
      first_name: string
      full_name: string
      inactive_at?: Date
      last_name: string
      name: string
      number?: string
      slug: string
      updated_at: Date
    }
  }
}
