// TypesFromSerializers CacheKey 9d8ef0d1ec412d4ea7554d448e4f1c30
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface ClientsPersisted {
      id: string
      active_at?: Date
      created_at: Date
      inactive_at?: Date
      number?: string
      person: PeoplePersisted
      person_id: string
      slug: string
      updated_at: Date
    }
  }
}
