// TypesFromSerializers CacheKey 4060b1b63122a9e0478c7c9496b93c1c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface ClientsPersisted {
      id: unknown
      active_at: unknown
      color: unknown
      color_mappings: unknown
      created_at: unknown
      inactive_at: unknown
      number: unknown
      person: PeoplePersisted
      person_id: unknown
      slug: unknown
      updated_at: unknown
    }
  }
}
