// TypesFromSerializers CacheKey 115a83c1b08acc1b403526b6eea3d159
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ClientsShallow {
      id: number
      created_at: string | Date
      number?: number
      settings: Record<string, string>
      updated_at: string | Date
    }
  }
}
