// TypesFromSerializers CacheKey 0d4f2c1657534ed00d8354dffb1370fc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ClientsShifts {
      id: number
      created_at: string | Date
      number?: number
      settings: Record<string, string>
      updated_at: string | Date
    }
  }
}
