// TypesFromSerializers CacheKey 8ef288b175cb1ce418495dfd6ea92c4b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface ClientsShow {
      id: number
      active_at?: string | Date
      created_at: string | Date
      inactive_at?: string | Date
      number?: string
      person: Person
      person_id: number
      updated_at: string | Date
    }
  }
}
