// TypesFromSerializers CacheKey 7eb4b64521754ef6532fb7d60b666251
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ClientsShow {
      id: number
      created_at: string | Date
      first_name?: string
      job_title_id?: number
      last_name?: string
      middle_name?: string
      person_type?: number
      slug: string
      updated_at: string | Date
      user_id?: number
    }
  }
}
