// TypesFromSerializers CacheKey db2aa0707d6898226377903584899e18
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ClientsSpotlight {
      id: string
      created_at: Date
      first_name: string
      full_name: string
      last_name: string
      name: string
      slug: string
      type: unknown
      updated_at: Date
    }
  }
}
