// TypesFromSerializers CacheKey c0681ba921999f95d9e328b2b645afc4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsEdit {
      id: unknown
      created_at: unknown
      generic_name: unknown
      name: unknown
      notes: unknown
      updated_at: unknown
    }
  }
}
