// TypesFromSerializers CacheKey 66ca53ce22b21577d575deb7d97ac9b7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsEdit {
      id: string
      created_at: Date
      generic_name?: string
      name: string
      notes?: string
      updated_at: Date
    }
  }
}
