// TypesFromSerializers CacheKey 8ef90a2d1ecc75fe72e5bb763b1aa1be
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsEdit {
      id: string
      created_at: string | Date
      generic_name?: string
      name: string
      notes?: string
      updated_at: string | Date
    }
  }
}
