// TypesFromSerializers CacheKey be1caecf2cf5bf56551a6ca7b9eb7586
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsFormData {
      id?: unknown
      generic_name: unknown
      name: unknown
      notes: unknown
    }
  }
}
