// TypesFromSerializers CacheKey e2a25c9cf763603254109a28392bbb55
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsFormData {
      id?: string
      generic_name?: string
      name: string
      notes?: string
    }
  }
}
