// TypesFromSerializers CacheKey 79eb63b72dd997a290078d772354c1d6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsFormData {
      id?: number
      generic_name?: string
      name?: string
      notes?: string
    }
  }
}
