// TypesFromSerializers CacheKey 3107ba37537d9fe417a5e493406d0d3d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsIndex {
      id: unknown
      created_at: unknown
      generic_name: unknown
      name: unknown
      notes: unknown
      updated_at: unknown
    }
  }
}
