// TypesFromSerializers CacheKey d134f33a8953cc9392630675e9b54608
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsIndex {
      id: unknown
      created_at: string | Date
      generic_name?: string
      name: string
      notes?: string
      updated_at: string | Date
    }
  }
}
