// TypesFromSerializers CacheKey 6cec148a7b7cc47b86d706d069386073
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsIndex {
      id: number
      created_at: string | Date
      generic_name?: string
      name?: string
      notes?: string
      updated_at: string | Date
    }
  }
}
