// TypesFromSerializers CacheKey d15b0c64ca6741d2b584aa4452ee8d68
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsShow {
      id: unknown
      created_at: string | Date
      generic_name?: string
      name: string
      notes?: string
      updated_at: string | Date
    }
  }
}
