// TypesFromSerializers CacheKey c270491c17c96dbeeac9adfc0e74b30b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsShow {
      id: string
      created_at: string | Date
      generic_name?: string
      name: string
      notes?: string
      updated_at: string | Date
    }
  }
}
