// TypesFromSerializers CacheKey 21324e0ad0f98eb917ca602d1e25befd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MedicationsShow {
      id: number
      created_at: string | Date
      generic_name?: string
      name?: string
      notes?: string
      updated_at: string | Date
    }
  }
}
