// TypesFromSerializers CacheKey eb12457623c1e521156deed37823ebbe
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RequirementRequirement {
      id?: unknown
      description: unknown
      name: unknown
      requirement_type_id: unknown
      scope_id: unknown
      scope_type: unknown
    }
  }
}
