// TypesFromSerializers CacheKey 14f55b1fec4431cf115031f2cc2c2f51
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface UsersEdit {
      id: unknown
      active: unknown
      created_at: unknown
      email: unknown
      person: PeoplePersisted
      slug: unknown
      updated_at: unknown
    }
  }
}
