// TypesFromSerializers CacheKey e343d3e0e3da63733bb68f495150f58b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface UsersEdit {
      id: string
      active: boolean
      created_at: string | Date
      email: string
      person: PeoplePersisted
      slug: string
      updated_at: string | Date
    }
  }
}
