// TypesFromSerializers CacheKey 06d4880d63e3d8cc66aa63968d366af0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface UsersEdit {
      id: string
      active: boolean
      created_at: Date
      email: string
      person: PeoplePersisted
      slug: string
      updated_at: Date
    }
  }
}
