// TypesFromSerializers CacheKey faf18ac130271775fb6689da6e81ae28
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface UsersFormData {
      id?: string
      slug?: string
      active: boolean
      email: string
    }
  }
}
