// TypesFromSerializers CacheKey ed9b032a68317f8daa4d5f641fca4826
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface UsersFormData {
      id?: number
      active: boolean
      email: string
      person: Person
    }
  }
}
