// TypesFromSerializers CacheKey 1598b1af59843cc9287aed01067292df
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface UsersFormData {
      id?: string
      active: boolean
      email: string
    }
  }
}
