// TypesFromSerializers CacheKey 816e12156f3dcc1f606c09a1aa966865
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface UsersIndex {
      id: string
      active: boolean
      created_at: string | Date
      email: string
      person: PeoplePersisted
      slug: string
      updated_at: string | Date
    }
  }
}
