// TypesFromSerializers CacheKey e67a6067dedc507ddfce349794a87931
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface UsersIndex {
      id: number
      active: boolean
      created_at: string | Date
      email: string
      person: Person
      updated_at: string | Date
    }
  }
}
