// TypesFromSerializers CacheKey 10f20d5364b9da3349e2680ba4a08a7b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type TablePreferences from '../../TablePreferences'
import type UserPreferences from '../../UserPreferences'
import type PeoplePersisted from '../People/Persisted'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersInertiaShare {
      id: string
      active: boolean
      created_at: string | Date
      email: string
      person: PeoplePersisted
      roles: Role[]
      slug: string
      table_preferences: TablePreferences
      updated_at: string | Date
      user_preferences: UserPreferences
    }
  }
}
