// TypesFromSerializers CacheKey 6cdc49b9c095875607c581c37ec64d92
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface UsersPersisted {
      id: unknown
      active: unknown
      created_at: unknown
      email: unknown
      person: PeoplePersisted
      slug: unknown
      updated_at: unknown
    }
  }
}
