// TypesFromSerializers CacheKey 1277b5c9261e997709a081bff80a9a28
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface UsersPersisted {
      id: string
      active: boolean
      created_at: string | Date
      email: string
      person: PeoplePersisted
      slug: string
      updated_at: string | Date
    }
  }
}
