// TypesFromSerializers CacheKey 5d0812185b4041440d503b1d36cefefd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ITablePreferences from '../../ITablePreferences'
import type IUserPreferences from '../../IUserPreferences'
import type Person from '../Person'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersShare {
      id: unknown
      active: boolean
      created_at: string | Date
      email: string
      person: Person
      roles: Role[]
      table_preferences: ITablePreferences
      updated_at: string | Date
      user_preferences: IUserPreferences
    }
  }
}
