// TypesFromSerializers CacheKey e5dd94a66244a0e778099e2c0b4e6bec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface UsersShow {
      id: unknown
      active: unknown
      created_at: unknown
      email: unknown
      person: PeoplePersisted
      slug: unknown
      updated_at: unknown
    }
  }
}
