// TypesFromSerializers CacheKey 82a67182fd08858610a1b1dd29bd0abc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface UsersShow {
      id: unknown
      active: boolean
      created_at: string | Date
      email: string
      person: Person
      updated_at: string | Date
    }
  }
}
