// TypesFromSerializers CacheKey 0485d4740abbdf8381d44c6168b09b86
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface UsersShow {
      id: number
      active: boolean
      created_at: string | Date
      email: string
      person: Person
      updated_at: string | Date
    }
  }
}
