// TypesFromSerializers CacheKey ec42c08c58cde55aa5d960426e2d7fbe
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface HouseholdsEdit {
      id: string
      slug?: string
      created_at: string | Date
      name: string
      updated_at: string | Date
    }
  }
}
