// TypesFromSerializers CacheKey 307e0358e21122b74a753b2394154fa1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface HouseholdsEdit {
      id: string
      created_at: string | Date
      name: string
      updated_at: string | Date
    }
  }
}
