// TypesFromSerializers CacheKey 94b828e94efe6f6343b7e68673a62d72
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ClientsPersisted from '../Clients/Persisted'

declare global {
  namespace Schema {
    interface HouseholdsEdit {
      id: string
      clients: ClientsPersisted[]
      created_at: Date
      name: string
      slug: string
      updated_at: Date
    }
  }
}
