// TypesFromSerializers CacheKey e9ad41e4504db5170dd6b880dfb55395
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface HouseholdsFormData {
      id?: number
      name?: string
    }
  }
}
