// TypesFromSerializers CacheKey 39013021730efe015d2f00d883f4d861
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface HouseholdsFormData {
      id?: string
      slug?: string
      name: string
    }
  }
}
