// TypesFromSerializers CacheKey 5a0fd08cc17924a2f2a0e45fca560f88
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface HouseholdsFormData {
      id?: string
      name: string
    }
  }
}
