// TypesFromSerializers CacheKey 0849133016763355490131cf208511b8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ClientsPersisted from '../Clients/Persisted'

declare global {
  namespace Schema {
    interface HouseholdsIndex {
      id: string
      clients: ClientsPersisted[]
      created_at: Date
      name: string
      slug: string
      updated_at: Date
    }
  }
}
