// TypesFromSerializers CacheKey 25026f44629a74bb83455f5a94cdd086
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface HouseholdsIndex {
      id: unknown
      created_at: string | Date
      name: string
      updated_at: string | Date
    }
  }
}
