// TypesFromSerializers CacheKey 5f969117bc9d67f1cd508a04f3e938d8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface HouseholdsIndex {
      id: number
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
