// TypesFromSerializers CacheKey 5bb4e0b6ab50992fd6a0fafea28fb7a8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ClientsPersisted from '../Clients/Persisted'

declare global {
  namespace Schema {
    interface HouseholdsPersisted {
      id: string
      clients: ClientsPersisted[]
      created_at: Date
      name: string
      slug: string
      updated_at: Date
    }
  }
}
