// TypesFromSerializers CacheKey 384c9b786e36d173148f9306c506d221
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface HouseholdsShow {
      id: unknown
      created_at: string | Date
      name: string
      updated_at: string | Date
    }
  }
}
