// TypesFromSerializers CacheKey 6640151cf38d5a264e51b66c7fbec92f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface HouseholdsShow {
      id: number
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
