// TypesFromSerializers CacheKey dbe5ca4ddd54f150777ad8af13c3662b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface HouseholdsShow {
      id: unknown
      slug?: unknown
      created_at: unknown
      name: unknown
      updated_at: unknown
    }
  }
}
