// TypesFromSerializers CacheKey 84fd4e41eadec857642ebc7e0107bc49
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesEdit {
      id: unknown
      category_id?: unknown
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
