// TypesFromSerializers CacheKey eec80c83df26038628a6da8924d7aef1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesEdit {
      id: unknown
      category_id?: unknown
      created_at: string | Date
      name: string
      updated_at: string | Date
    }
  }
}
