// TypesFromSerializers CacheKey a0cd605ffe465f729a913d9009a7a127
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesEdit {
      id: number
      category_id: number
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
