// TypesFromSerializers CacheKey 86e4a792db080b0fcc709ad1cf7bbc17
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesFormData {
      id?: unknown
      category_id?: unknown
      name?: string
    }
  }
}
