// TypesFromSerializers CacheKey bd203642b8468fe17451ee7b4da87e95
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesFormData {
      id?: unknown
      category_id?: unknown
      name: string
    }
  }
}
