// TypesFromSerializers CacheKey 9dc9d4a13068de83abbd6f7c5d1d1451
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesFormData {
      id?: string
      category_id?: string
      name: string
    }
  }
}
