// TypesFromSerializers CacheKey 698ecdfa8dfcdfd8395cf73acc6b1e04
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesIndex {
      id: string
      category_id?: string
      created_at: string | Date
      name: string
      updated_at: string | Date
    }
  }
}
