// TypesFromSerializers CacheKey 50adf698285dfce8c210070ee7a5e66c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesIndex {
      id: number
      category_id: number
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
