// TypesFromSerializers CacheKey c1d216b6978a111f91d776a095992655
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesShow {
      id: unknown
      category_id?: unknown
      created_at: string | Date
      name: string
      updated_at: string | Date
    }
  }
}
