// TypesFromSerializers CacheKey 917b57518ad21fa58ef034657e516bc7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesShow {
      id: number
      category_id: number
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
