// TypesFromSerializers CacheKey b02f15a61d48fe926bd32a0484a4cce8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentTypesShow {
      id: string
      category_id?: string
      created_at: Date
      name: string
      updated_at: Date
    }
  }
}
