---
translations:
  - file: "app/frontend/lib/locales/:locale.json"
    patterns:
      - "*"
      - "!*.activerecord.*"
      - "!*.faker.*"
      - "!*.errors.*"
      - "!*.number.nth.*"
      - "!*.good_job.*"

