# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@inertiajs/inertia", to: "https://ga.jspm.io/npm:@inertiajs/inertia@0.10.1/dist/index.js"
pin "@inertiajs/inertia-react", to: "https://ga.jspm.io/npm:@inertiajs/inertia-react@0.7.1/dist/index.js"
pin "#lib/adapters/http.js", to: "https://ga.jspm.io/npm:axios@0.21.4/lib/adapters/xhr.js"
pin "axios", to: "https://ga.jspm.io/npm:axios@0.21.4/index.js"
pin "call-bind/callBound", to: "https://ga.jspm.io/npm:call-bind@1.0.2/callBound.js"
pin "deepmerge", to: "https://ga.jspm.io/npm:deepmerge@4.2.2/dist/cjs.js"
pin "function-bind", to: "https://ga.jspm.io/npm:function-bind@1.1.1/index.js"
pin "get-intrinsic", to: "https://ga.jspm.io/npm:get-intrinsic@1.1.1/index.js"
pin "has", to: "https://ga.jspm.io/npm:has@1.0.3/src/index.js"
pin "has-symbols", to: "https://ga.jspm.io/npm:has-symbols@1.0.2/index.js"
pin "lodash.isequal", to: "https://ga.jspm.io/npm:lodash.isequal@4.5.0/index.js"
pin "object-assign", to: "https://ga.jspm.io/npm:object-assign@4.1.1/index.js"
pin "object-inspect", to: "https://ga.jspm.io/npm:object-inspect@1.11.0/index.js"
pin "object-inspect/util.inspect.js", to: "https://ga.jspm.io/npm:object-inspect@1.11.0/util.inspect.js"
pin "process", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.14/nodelibs/browser/process-production.js"
pin "qs", to: "https://ga.jspm.io/npm:qs@6.10.2/lib/index.js"
pin "react", to: "https://ga.jspm.io/npm:react@17.0.2/index.js"
pin "side-channel", to: "https://ga.jspm.io/npm:side-channel@1.0.4/index.js"
pin "util", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.14/nodelibs/browser/util.js"
pin "@inertiajs/progress", to: "https://ga.jspm.io/npm:@inertiajs/progress@0.2.6/dist/index.js"
pin "nprogress", to: "https://ga.jspm.io/npm:nprogress@0.2.0/nprogress.js"
