// TypesFromSerializers CacheKey 1e6ffd2c75003390540280a4d2ab13ef
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AddressesEdit {
      id: number
      address?: string
      address_2?: string
      category_id?: number
      city?: string
      contact_id: number
      country?: number
      created_at: string | Date
      notes?: string
      postal?: string
      region?: string
      title?: string
      updated_at: string | Date
    }
  }
}
