// TypesFromSerializers CacheKey 424ad4604803d078ec2f53bc084b9132
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AddressesFormData {
      id?: number
      address?: string
      address_2?: string
      category_id?: number
      city?: string
      contact_id: number
      country?: number
      notes?: string
      postal?: string
      region?: string
      title?: string
    }
  }
}
