// TypesFromSerializers CacheKey 9580c49b44b4dbe2e38379876b68a426
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AddressesIndex {
      id: number
      address?: string
      address_2?: string
      category_id?: number
      city?: string
      contact_id: number
      country?: number
      created_at: string | Date
      notes?: string
      postal?: string
      region?: string
      title?: string
      updated_at: string | Date
    }
  }
}
