// TypesFromSerializers CacheKey 364ccbe6d352de597fd72480349569b2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesOptions {
      id: string
      created_at: Date
      name: string
      slug: string
      updated_at: Date
    }
  }
}
