// TypesFromSerializers CacheKey 8176247bcb2bc2d65d414d632263a50e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeTrainingsEdit {
      id: unknown
      active_on: unknown
      created_at: unknown
      description: unknown
      estimated_minutes: unknown
      inactive_on: unknown
      name: unknown
      updated_at: unknown
    }
  }
}
