// TypesFromSerializers CacheKey daf48f7fadbedde4af2a430c382d2359
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeTrainingsFormData {
      id?: unknown
      active_on: unknown
      description: unknown
      estimated_minutes: unknown
      inactive_on: unknown
      name: unknown
    }
  }
}
