// TypesFromSerializers CacheKey c7e3e9d5ff718d31a87b7d4e526ebff9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeTrainingsIndex {
      id: unknown
      active_on: unknown
      created_at: unknown
      description: unknown
      estimated_minutes: unknown
      inactive_on: unknown
      name: unknown
      updated_at: unknown
    }
  }
}
