// TypesFromSerializers CacheKey c042bdcdfda84ed0bd7f83f10c0178e5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeTrainingsOptions {
      id: string
      created_at: Date
      name?: string
      updated_at: Date
    }
  }
}
