// TypesFromSerializers CacheKey 8365568bb2cb11bbc2b9d8a807c6e238
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeTrainingsPersisted {
      id: unknown
      active_on: unknown
      created_at: unknown
      description: unknown
      estimated_minutes: unknown
      inactive_on: unknown
      name: unknown
      updated_at: unknown
    }
  }
}
