// TypesFromSerializers CacheKey 11cb7d8b303492aaa4288b56a7c84c9a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeTrainingsShow {
      id: unknown
      active_on: unknown
      created_at: unknown
      description: unknown
      estimated_minutes: unknown
      inactive_on: unknown
      name: unknown
      updated_at: unknown
    }
  }
}
