// TypesFromSerializers CacheKey bf6181844336e34cc5673a7b05456aba
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeTrainingsSpotlight {
      id: string
      created_at: Date
      name?: string
      type: unknown
      updated_at: Date
    }
  }
}
