// TypesFromSerializers CacheKey a656667617388119613f148836cc50d1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RequirementRequirementsEdit {
      id: unknown
      created_at: unknown
      description: unknown
      name: unknown
      requirement_type_id: unknown
      scope_id: unknown
      scope_type: unknown
      updated_at: unknown
    }
  }
}
