// TypesFromSerializers CacheKey 78288aaa498cbb989514c6f5d677b4fb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RequirementRequirementsFormData {
      id?: unknown
      description: unknown
      name: unknown
      requirement_type_id: unknown
      scope_id: unknown
      scope_type: unknown
    }
  }
}
