// TypesFromSerializers CacheKey 68f379a235b1561a5193865f7a66b871
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RequirementRequirementsPersisted {
      id: unknown
      created_at: unknown
      description: unknown
      name: unknown
      requirement_type_id: unknown
      scope_id: unknown
      scope_type: unknown
      updated_at: unknown
    }
  }
}
