// TypesFromSerializers CacheKey 50e508b6a2b7eea7abc477f5f4dff56d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleEdit {
      id: string
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      nick_name?: string
      slug: string
      updated_at: string | Date
      user_id?: string
    }
  }
}
