// TypesFromSerializers CacheKey 6723ff120d795d3bb306ce29c115c032
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleEdit {
      id: string
      agency_role: string
      created_at: Date
      first_name?: string
      last_name?: string
      login_enabled: boolean
      middle_name?: string
      name: string
      nick_name?: string
      slug: string
      updated_at: Date
      user_id?: string
    }
  }
}
