// TypesFromSerializers CacheKey c478f2b2714fc402f1275d1e27820e2f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleEdit {
      id: number
      created_at: string | Date
      first_name?: string
      job_title_id?: number
      last_name?: string
      middle_name?: string
      person_type?: number
      slug: string
      updated_at: string | Date
      user_id?: number
    }
  }
}
