// TypesFromSerializers CacheKey 894d57bee6976681376691ebc4b471af
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleFormData {
      id?: number
      first_name?: string
      full_name: string
      last_name?: string
      middle_name?: string
      nick_name?: string
      user_id?: number
    }
  }
}
