// TypesFromSerializers CacheKey 0477ff0d190b6a6438178169f0917ac2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleFormData {
      id?: unknown
      slug?: unknown
      first_name: unknown
      last_name: unknown
      middle_name: unknown
      name: string
      nick_name: unknown
      user_id: unknown
    }
  }
}
