// TypesFromSerializers CacheKey 0c20bd956dc923710200c196a4618e99
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleFormData {
      id?: string
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      nick_name?: string
      user_id?: string
    }
  }
}
