// TypesFromSerializers CacheKey d0d825c710be2949354ca7b72cf2fc3f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleIndex {
      id: unknown
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      nick_name?: string
      updated_at: string | Date
      user_id?: unknown
    }
  }
}
