// TypesFromSerializers CacheKey 731e27d211b6bbc62d7c8d10326c85c4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleIndex {
      id: unknown
      created_at: unknown
      first_name: unknown
      last_name: unknown
      middle_name: unknown
      name: string
      nick_name: unknown
      slug: unknown
      updated_at: unknown
      user_id: unknown
    }
  }
}
