// TypesFromSerializers CacheKey 93c948ef3ded59dd705611b208a68da8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleIndex {
      id: string
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      nick_name?: string
      slug: string
      updated_at: string | Date
      user_id?: string
    }
  }
}
