// TypesFromSerializers CacheKey eb7c39870bae1679f19bdb85cb9c50b1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeoplePersisted {
      id: string
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      nick_name?: string
      slug: string
      updated_at: string | Date
      user_id?: string
    }
  }
}
