// TypesFromSerializers CacheKey cf386c4c5680d3b5ef602edcdf6e2bfc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeoplePersisted {
      id: string
      agency_role: string
      created_at: Date
      first_name?: string
      last_name?: string
      login_enabled: boolean
      middle_name?: string
      name: string
      nick_name?: string
      slug: string
      updated_at: Date
      user_id?: string
    }
  }
}
