// TypesFromSerializers CacheKey 0932d498564c4d1ac93d6a258e5e24cf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeoplePersisted {
      id: string
      created_at: Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      nick_name?: string
      slug: string
      updated_at: Date
      user_id?: string
    }
  }
}
