// TypesFromSerializers CacheKey e0b36526d2b5a32a7a391726803411c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleShallow {
      id?: number
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      updated_at: string | Date
    }
  }
}
