// TypesFromSerializers CacheKey 29ec395d62da99a82f4ee0ac710274c5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleShow {
      id: number
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      nick_name?: string
      updated_at: string | Date
      user_id?: number
    }
  }
}
