// TypesFromSerializers CacheKey 93b182837bd70a6c45166b1b8a40ae45
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ContactsPersisted from '../Contacts/Persisted'

declare global {
  namespace Schema {
    interface PeopleShow {
      id: string
      contact: ContactsPersisted
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      nick_name?: string
      slug: string
      updated_at: string | Date
      user_id?: string
    }
  }
}
