// TypesFromSerializers CacheKey e927f555d38f0554e42631a033dc4943
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleShow {
      id: string
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      nick_name?: string
      slug: string
      updated_at: string | Date
      user_id?: string
    }
  }
}
