// TypesFromSerializers CacheKey a3ce067ab2da93023173b14c70392670
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsEdit {
      id: string
      agency_notified_at?: Date
      client_id: string
      created_at: Date
      description?: string
      incident_type_id: string
      location?: string
      occurred_at?: Date
      reported_at?: Date
      reported_by_id: string
      reported_to_id: string
      updated_at: Date
    }
  }
}
