// TypesFromSerializers CacheKey aaf7eb2b8752f446213abc57c9009d02
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsFormData {
      id?: unknown
      agency_notified_at: unknown
      category_id: unknown
      client_id: unknown
      description: unknown
      location: unknown
      occurred_at: unknown
      reported_at: unknown
      reported_by_id: unknown
      reported_to_id: unknown
    }
  }
}
