// TypesFromSerializers CacheKey 7a08e77824911fca4faa3ae9a3ef40ce
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsFormData {
      id?: number
      agency_notified_at?: string | Date
      client_id: number
      description?: string
      incident_type_id: number
      location?: string
      occurred_at?: string | Date
      reported_at?: string | Date
      reported_by_id: number
      reported_to_id: number
    }
  }
}
