// TypesFromSerializers CacheKey 1fd35052002fd82b93c8299a6f506347
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsFormData {
      id?: string
      agency_notified_at?: string | Date
      client_id: string
      description?: string
      incident_type_id: string
      location?: string
      occurred_at?: string | Date
      reported_at?: string | Date
      reported_by_id: string
      reported_to_id: string
    }
  }
}
