// TypesFromSerializers CacheKey 401b2b1de485c06af6600bf3725dfe9f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsIndex {
      id: string
      agency_notified_at?: Date
      category_id: string
      client_id: string
      created_at: Date
      description?: string
      location?: string
      occurred_at?: Date
      reported_at?: Date
      reported_by_id: string
      reported_to_id: string
      updated_at: Date
    }
  }
}
