// TypesFromSerializers CacheKey ce75ef0ce49d33f6b08c87a84a933534
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsIndex {
      id: unknown
      agency_notified_at: unknown
      category_id: unknown
      client_id: unknown
      created_at: unknown
      description: unknown
      location: unknown
      occurred_at: unknown
      reported_at: unknown
      reported_by_id: unknown
      reported_to_id: unknown
      updated_at: unknown
    }
  }
}
