// TypesFromSerializers CacheKey 8afd10cb4fbd3527373e072aa68456b4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsIndex {
      id: number
      agency_notified_at?: string | Date
      client_id: number
      created_at: string | Date
      description?: string
      incident_type_id: number
      location?: string
      occurred_at?: string | Date
      reported_at?: string | Date
      reported_by_id: number
      reported_to_id: number
      updated_at: string | Date
    }
  }
}
