// TypesFromSerializers CacheKey 1c2c274fb6793e1dbe94672e3837604c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsPersisted {
      id: string
      agency_notified_at?: Date
      category_id: string
      client_id: string
      created_at: Date
      description?: string
      location?: string
      occurred_at?: Date
      reported_at?: Date
      reported_by_id: string
      reported_to_id: string
      updated_at: Date
    }
  }
}
