// TypesFromSerializers CacheKey 5225412f3d82696fc70d51f8a507227e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsShow {
      id: number
      agency_notified_at?: string | Date
      client_id: number
      created_at: string | Date
      description?: string
      incident_type_id: number
      location?: string
      occurred_at?: string | Date
      reported_at?: string | Date
      reported_by_id: number
      reported_to_id: number
      updated_at: string | Date
    }
  }
}
