// TypesFromSerializers CacheKey 693a257ddcc20b46257bc39d03fa8440
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsShow {
      id: unknown
      agency_notified_at?: string | Date
      client_id: unknown
      created_at: string | Date
      description?: string
      incident_type_id: unknown
      location?: string
      occurred_at?: string | Date
      reported_at?: string | Date
      reported_by_id: unknown
      reported_to_id: unknown
      updated_at: string | Date
    }
  }
}
