// TypesFromSerializers CacheKey e27ff6d449cacbbb442a531766ed9fcc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IncidentReportsShow {
      id: string
      agency_notified_at?: Date
      client_id: string
      created_at: Date
      description?: string
      incident_type_id: string
      location?: string
      occurred_at?: Date
      reported_at?: Date
      reported_by_id: string
      reported_to_id: string
      updated_at: Date
    }
  }
}
