// TypesFromSerializers CacheKey 7697c1325d1d7ca6f6ea92b2f14f6889
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarRecurringPattern from './RecurringPattern'
import type Shift from '../Shift'

declare global {
  namespace Schema {
    interface CalendarEvent {
      id?: string
      created_at: Date
      created_by_id: string
      ends_at?: Date
      name?: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: Shift
      starts_at?: Date
      updated_at: Date
    }
  }
}
