// TypesFromSerializers CacheKey 38b36ac25baee0909fe28e9565b66e66
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarRecurringPattern from './RecurringPattern'
import type Shift from '../Shift'

declare global {
  namespace Schema {
    interface CalendarEvent {
      id?: string
      category_id: unknown
      created_at: Date
      created_by_id: string
      ends_at?: Date
      name: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: Shift
      starts_at?: Date
      updated_at: Date
    }
  }
}
// TypesFromSerializers CacheKey 38b36ac25baee0909fe28e9565b66e66
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarRecurringPattern from './RecurringPattern'
import type Shift from '../Shift'

declare global {
  namespace Schema {
    interface CalendarEvent {
      id?: string
      category_id: unknown
      created_at: Date
      created_by_id: string
      ends_at?: Date
      name: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: Shift
      starts_at?: Date
      updated_at: Date
    }
  }
}
