// TypesFromSerializers CacheKey 96ecf450d71e81938f566d6a25b632ac
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarRecurringPattern from './RecurringPattern'
import type Shift from '../Shift'

declare global {
  namespace Schema {
    interface CalendarEvent {
      id?: string
      created_at: Date
      created_by_id: string
      ends_at?: Date
      name: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: Shift
      starts_at?: Date
      updated_at: Date
    }
  }
}
