// TypesFromSerializers CacheKey 3b7183762905721e1704ff0e5f56d275
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CalendarRecurringPattern {
      id?: string
      day_of_month?: number
      day_of_week?: number
      end_date?: number
      max_occurrences?: number
      month_of_year?: number
      offset: number
      recurring_type: "daily" | "weekly" | "monthly" | "yearly"
      week_of_month?: number
    }
  }
}
