// TypesFromSerializers CacheKey 0d4e86d1f43d076a499dcb26fdb2f711
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EmployeeJobTitle {
      id?: unknown
      slug?: unknown
      description: unknown
      name: unknown
    }
  }
}
