// TypesFromSerializers CacheKey d5e9188247cb89ba727c79c3188f677e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'

declare global {
  namespace Schema {
    interface PhonesEdit {
      id: string
      category: Category
      created_at: Date
      extension?: string
      name?: string
      number: string
      updated_at: Date
    }
  }
}
