// TypesFromSerializers CacheKey 2eeca82cab69de506797b38c9991c8f9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'

declare global {
  namespace Schema {
    interface PhonesIndex {
      id: string
      category: Category
      created_at: Date
      extension?: string
      name?: string
      number: string
      updated_at: Date
    }
  }
}
