// TypesFromSerializers CacheKey 5f9096c5f42cab6c51a15cbf923072d8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'

declare global {
  namespace Schema {
    interface PhonesPersisted {
      id: string
      category: Category
      created_at: Date
      extension?: string
      name?: string
      number: string
      updated_at: Date
    }
  }
}
