// TypesFromSerializers CacheKey b1270fa4eb0e1e3c3681107d2f0ac1a3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'

declare global {
  namespace Schema {
    interface PhonesShow {
      id: string
      category: Category
      created_at: Date
      extension?: string
      name?: string
      number: string
      updated_at: Date
    }
  }
}
