// TypesFromSerializers CacheKey d04707506dedb5d02fa3004f362da78d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TrainingsEdit {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
