// TypesFromSerializers CacheKey ef2d18f4d9cf8e82ff8449a3dd4e015c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TrainingsFormData {
      id?: unknown
    }
  }
}
