// TypesFromSerializers CacheKey 31d7c87ee57505d797d351d59852a57d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TrainingsIndex {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
