// TypesFromSerializers CacheKey 4155e1b160d4603659eac2411ea80761
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TrainingsIndex {
      id: string
      active_on?: Date
      created_at: Date
      description?: string
      estimated_minutes?: number
      inactive_on?: Date
      name?: string
      updated_at: Date
    }
  }
}
