// TypesFromSerializers CacheKey addd3cbb01b36cf9305039256d955008
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TrainingsPersisted {
      id: unknown
      created_at: unknown
      updated_at: unknown
    }
  }
}
