// TypesFromSerializers CacheKey 7ae7628b010ca258759f7079fa3983c6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TrainingsPersisted {
      id: string
      active_on?: Date
      created_at: Date
      description?: string
      estimated_minutes?: number
      inactive_on?: Date
      name?: string
      updated_at: Date
    }
  }
}
