// TypesFromSerializers CacheKey 2935bc14b9996a0ba4a0c0bdff27f39d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EventParticipantsIndex {
      id?: string
      calendar_event_id: string
      participant_id: string
      participant_type: string
    }
  }
}
