// TypesFromSerializers CacheKey 2a8473499a025cc18942c55bc9cc7941
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EventParticipantsPersisted {
      id: string
      calendar_event_id: string
      created_at: Date
      participant_id: string
      participant_type: string
      updated_at: Date
    }
  }
}
