// TypesFromSerializers CacheKey 230443a6340734405d16812968dd4c4e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EventParticipantsShow {
      id?: string
      calendar_event_id: string
      participant_id: string
      participant_type: string
    }
  }
}
