// TypesFromSerializers CacheKey 7a772eae554d888cc9004af168b91ae6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsEdit {
      id: string
      contactable_id: string
      contactable_type: string
      created_at: string | Date
      notes?: string
      primary_address_id?: string
      primary_email_id?: string
      primary_phone_id?: string
      updated_at: string | Date
    }
  }
}
