// TypesFromSerializers CacheKey 13322e5eb8042bed96fab1e54d90312d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsEdit {
      id: number
      contactable_id: number
      contactable_type: string
      created_at: string | Date
      notes?: string
      primary_address_id?: number
      primary_email_id?: number
      primary_phone_id?: number
      updated_at: string | Date
    }
  }
}
