// TypesFromSerializers CacheKey 79b2ee55ce8f2c0a4f626b5e982df0c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsFormData {
      id?: string
      contactable_id: string
      contactable_type: string
      notes?: string
      primary_address_id?: string
      primary_email_id?: string
      primary_phone_id?: string
    }
  }
}
