// TypesFromSerializers CacheKey ef764cbfe7db8cb555be117091a3cbcb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsFormData {
      id?: unknown
      contactable_id: unknown
      contactable_type: unknown
      notes: unknown
      primary_address_id: unknown
      primary_email_id: unknown
      primary_phone_id: unknown
    }
  }
}
