// TypesFromSerializers CacheKey 80f561ed6d04e1b4677c2d1edf8df53b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsIndex {
      id: string
      contactable_id: string
      contactable_type: string
      created_at: Date
      notes?: string
      primary_address_id?: string
      primary_email_id?: string
      primary_phone_id?: string
      updated_at: Date
    }
  }
}
