// TypesFromSerializers CacheKey 4a6ffeb9e11cc049127e9aa6ea605d4b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsIndex {
      id: number
      contactable_id: number
      contactable_type: string
      created_at: string | Date
      notes?: string
      primary_address_id?: number
      primary_email_id?: number
      primary_phone_id?: number
      updated_at: string | Date
    }
  }
}
