// TypesFromSerializers CacheKey 6483a9548b26a2edad64a9c15a120647
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsIndex {
      id: unknown
      contactable_id: unknown
      contactable_type: string
      created_at: string | Date
      notes?: string
      primary_address_id?: unknown
      primary_email_id?: unknown
      primary_phone_id?: unknown
      updated_at: string | Date
    }
  }
}
