// TypesFromSerializers CacheKey 5df382099b378ab72764c6e5802af5c6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Address from '../Address'
import type Email from '../Email'
import type Phone from '../Phone'

declare global {
  namespace Schema {
    interface ContactsPersisted {
      id: string
      addresses: Address[]
      contactable_id: string
      contactable_type: string
      created_at: Date
      emails: Email[]
      notes?: string
      phones: Phone[]
      primary_address_id?: string
      primary_email_id?: string
      primary_phone_id?: string
      updated_at: Date
    }
  }
}
