// TypesFromSerializers CacheKey bcee140f100ec4af9b52371a1809aa34
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AddressesPersisted from '../Addresses/Persisted'
import type EmailsPersisted from '../Emails/Persisted'
import type PhonesPersisted from '../Phones/Persisted'

declare global {
  namespace Schema {
    interface ContactsPersisted {
      id: string
      addresses: AddressesPersisted[]
      contactable_id: string
      contactable_type: string
      created_at: Date
      emails: EmailsPersisted[]
      notes?: string
      phones: PhonesPersisted[]
      primary_address_id?: string
      primary_email_id?: string
      primary_phone_id?: string
      updated_at: Date
    }
  }
}
