// TypesFromSerializers CacheKey a1f5725c20d763e15332ea95d81bc115
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsShow {
      id: string
      contactable_id: string
      contactable_type: string
      created_at: Date
      notes?: string
      primary_address_id?: string
      primary_email_id?: string
      primary_phone_id?: string
      updated_at: Date
    }
  }
}
