// TypesFromSerializers CacheKey 6b1770d587551805c619a55d5f3fa861
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsShow {
      id: unknown
      contactable_id: unknown
      contactable_type: unknown
      created_at: unknown
      notes: unknown
      primary_address_id: unknown
      primary_email_id: unknown
      primary_phone_id: unknown
      updated_at: unknown
    }
  }
}
