// TypesFromSerializers CacheKey 43fdbbb2c09ea23d8629ba1e23449d27
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContactsShow {
      id: number
      contactable_id: number
      contactable_type: string
      created_at: string | Date
      notes?: string
      primary_address_id?: number
      primary_email_id?: number
      primary_phone_id?: number
      updated_at: string | Date
    }
  }
}
