// TypesFromSerializers CacheKey 01dfa6d4aa83c9a5910c164e10990abf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarRecurringPattern from '../RecurringPattern'
import type ShiftsClient from '../../Shifts/Client'

declare global {
  namespace Schema {
    interface CalendarEventsClient {
      id: string
      created_at: Date
      created_by_id?: string
      ends_at: Date
      name?: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: ShiftsClient
      starts_at: Date
      updated_at: Date
    }
  }
}
