// TypesFromSerializers CacheKey 9b01539594703c257066940fc5607d76
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarRecurringPattern from '../RecurringPattern'

declare global {
  namespace Schema {
    interface CalendarEventsEdit {
      id?: string
      category_id?: string
      created_at: Date
      created_by_id: string
      employee_id?: string
      ends_at?: Date
      name: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      starts_at?: Date
      updated_at: Date
    }
  }
}
