// TypesFromSerializers CacheKey 18450b8e0b262ed4522e7124c5456a74
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ClientsPersisted from '../../Clients/Persisted'
import type CalendarRecurringPattern from '../RecurringPattern'
import type ShiftsEmployee from '../../Shifts/Employee'

declare global {
  namespace Schema {
    interface CalendarEventsEmployee {
      id: string
      clients: ClientsPersisted[]
      created_at: Date
      created_by_id?: string
      ends_at: Date
      name?: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: ShiftsEmployee
      starts_at: Date
      updated_at: Date
    }
  }
}
