// TypesFromSerializers CacheKey a306be8a1d62226a69b6d82e8bd2b6f7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarRecurringPattern from '../RecurringPattern'
import type Shift from '../../Shift'

declare global {
  namespace Schema {
    interface CalendarEventsFormData {
      id?: string
      created_at: Date
      created_by_id?: string
      ends_at?: Date
      name?: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: Shift
      starts_at?: Date
      updated_at: Date
    }
  }
}
