// TypesFromSerializers CacheKey 5d0c456fad93e600041fd32fcb386827
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarRecurringPattern from '../RecurringPattern'

declare global {
  namespace Schema {
    interface CalendarEventsFormData {
      id?: string
      category_id?: string
      created_at: Date
      created_by_id: string
      employee_id?: string
      ends_at?: Date
      name: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      starts_at?: Date
      updated_at: Date
    }
  }
}
