// TypesFromSerializers CacheKey 2ea77722766a2c99b18878b43aee5940
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ClientsPersisted from '../../Clients/Persisted'
import type EventParticipant from '../../EventParticipant'
import type CalendarRecurringPattern from '../RecurringPattern'
import type ShiftsClient from '../../Shifts/Client'

declare global {
  namespace Schema {
    interface CalendarEventsHousehold {
      id: string
      all_day: boolean
      clients: ClientsPersisted[]
      created_at: Date
      created_by_id?: string
      ends_at: Date
      event_participants: EventParticipant[]
      name?: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: ShiftsClient
      starts_at: Date
      updated_at: Date
    }
  }
}
