// TypesFromSerializers CacheKey 1a4408048bc26f37eec444466a016d55
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarRecurringPattern from '../RecurringPattern'
import type Shift from '../../Shift'

declare global {
  namespace Schema {
    interface CalendarEventsIndex {
      id: string
      created_at: Date
      created_by_id?: string
      ends_at: Date
      name?: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: Shift
      starts_at: Date
      updated_at: Date
    }
  }
}
