// TypesFromSerializers CacheKey 224ea0e2d416e07345408df05dffdd7d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CalendarRecurringPattern from '../RecurringPattern'
import type Shift from '../../Shift'

declare global {
  namespace Schema {
    interface CalendarEventsPersisted {
      id: string
      created_at: Date
      created_by_id?: string
      ends_at: Date
      name?: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: Shift
      starts_at: Date
      updated_at: Date
    }
  }
}
