// TypesFromSerializers CacheKey 32dc9f84fd29383b2598035526060425
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type EmployeesPersisted from '../../Employees/Persisted'
import type CalendarRecurringPattern from '../RecurringPattern'
import type Shift from '../../Shift'

declare global {
  namespace Schema {
    interface CalendarEventsShow {
      id?: string
      category_id?: string
      created_at: Date
      created_by_id: string
      employee: EmployeesPersisted
      ends_at?: Date
      name: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      shift: Shift
      starts_at?: Date
      updated_at: Date
    }
  }
}
