// TypesFromSerializers CacheKey 8688913631f8db147eef3e5f139332d1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type EmployeesPersisted from '../../Employees/Persisted'
import type CalendarRecurringPattern from '../RecurringPattern'

declare global {
  namespace Schema {
    interface CalendarEventsShow {
      id?: string
      category_id?: string
      created_at: Date
      created_by_id: string
      employee: EmployeesPersisted
      employee_id?: string
      ends_at?: Date
      name: string
      parent_id?: string
      recurring_patterns: CalendarRecurringPattern[]
      starts_at?: Date
      updated_at: Date
    }
  }
}
