// TypesFromSerializers CacheKey aec4e2a0de71ed2896910670aa3e2819
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesEdit {
      id: string
      created_at: Date
      name?: string
      resource_id?: string
      resource_type?: string
      updated_at: Date
    }
  }
}
