// TypesFromSerializers CacheKey 35eaeb52a06410fda4fc83077d76f1cb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesEdit {
      id: unknown
      created_at: string | Date
      name?: string
      resource_id?: unknown
      resource_type?: string
      updated_at: string | Date
    }
  }
}
