// TypesFromSerializers CacheKey c8dfc966169bb27acc71f005492e57be
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesEdit {
      id: string
      created_at: string | Date
      name?: string
      resource_id?: string
      resource_type?: string
      updated_at: string | Date
    }
  }
}
