// TypesFromSerializers CacheKey 62ef98cf0c346ca5dc2158364ae6e111
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesFormData {
      id?: unknown
      name?: string
      resource_id?: unknown
      resource_type?: string
    }
  }
}
