// TypesFromSerializers CacheKey 512c4396dfe997e163118433cd8866b9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesFormData {
      id?: unknown
      name: unknown
      resource_id: unknown
      resource_type: unknown
    }
  }
}
