// TypesFromSerializers CacheKey 4157117758f93e9e2e1c4075bbf9e300
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesFormData {
      id?: string
      name?: string
      resource_id?: string
      resource_type?: string
    }
  }
}
