// TypesFromSerializers CacheKey 91f9c8746f18b0d7e42cea54877ff81b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesIndex {
      id: string
      created_at: Date
      name?: string
      resource_id?: string
      resource_type?: string
      updated_at: Date
    }
  }
}
