// TypesFromSerializers CacheKey c1e5333769e56604e651faecab063b13
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesIndex {
      id: unknown
      created_at: unknown
      name: unknown
      resource_id: unknown
      resource_type: unknown
      updated_at: unknown
    }
  }
}
