// TypesFromSerializers CacheKey f3565860b2d97d258b8e744caeb8876a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesIndex {
      id: unknown
      created_at: string | Date
      name?: string
      resource_id?: unknown
      resource_type?: string
      updated_at: string | Date
    }
  }
}
