// TypesFromSerializers CacheKey ffdcb38db684e5e3e3b349375e3c61c3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesShow {
      id: string
      created_at: Date
      name?: string
      resource_id?: string
      resource_type?: string
      updated_at: Date
    }
  }
}
