// TypesFromSerializers CacheKey e937d99eca2d8f897a0e9dae46313627
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RolesShow {
      id: string
      created_at: string | Date
      name?: string
      resource_id?: string
      resource_type?: string
      updated_at: string | Date
    }
  }
}
