// TypesFromSerializers CacheKey c7ffcd4c9e0f9dd1d174b290630a671c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsEdit {
      id: string
      created_at: Date
      expires_at?: Date
      extra_fields?: Record<string, string>
      identificationable_id: string
      identificationable_type: string
      issued_at?: Date
      notes?: string
      number?: number
      type?: number
      updated_at: Date
    }
  }
}
