// TypesFromSerializers CacheKey 5c49d6c294f14c53efb9611482d2efd2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsEdit {
      id: unknown
      created_at: unknown
      expires_at: unknown
      extra_fields: unknown
      identificationable_id: unknown
      identificationable_type: unknown
      issued_at: unknown
      notes: unknown
      number: unknown
      type: unknown
      updated_at: unknown
    }
  }
}
