// TypesFromSerializers CacheKey 960c62b3c13a9559254627b0ad5cd651
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsEdit {
      id: unknown
      created_at: string | Date
      expires_at?: string | Date
      extra_fields?: Record<string, string>
      identificationable_id: unknown
      identificationable_type: string
      issued_at?: string | Date
      notes?: string
      number?: number
      type?: number
      updated_at: string | Date
    }
  }
}
