// TypesFromSerializers CacheKey 2527236e5445691966a1676ffd15ff9e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsFormData {
      id?: string
      expires_at?: Date
      extra_fields?: Record<string, string>
      identificationable_id: string
      identificationable_type: string
      issued_at?: Date
      notes?: string
      number?: number
      type?: number
    }
  }
}
