// TypesFromSerializers CacheKey 74ebef5fb43dd278cb1ceb308118ff2f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsFormData {
      id?: string
      expires_at?: Date
      extra_fields?: Record<string, string>
      id_type: "drivers_license" | "passport" | "state_id" | "military_id" | "employee_id" | "other"
      identificationable_id: string
      identificationable_type: string
      issued_at?: Date
      notes?: string
      number?: string
    }
  }
}
