// TypesFromSerializers CacheKey 760aa31f78bd99ceed0a12dd2d4ed36a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsFormData {
      id?: string
      expires_at?: string | Date
      extra_fields?: Record<string, string>
      identificationable_id: string
      identificationable_type: string
      issued_at?: string | Date
      notes?: string
      number?: number
      type?: number
    }
  }
}
