// TypesFromSerializers CacheKey f4bdd20edefaf409592eb69fff60f7ae
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsIndex {
      id: unknown
      created_at: unknown
      expires_at: unknown
      extra_fields: unknown
      identificationable_id: unknown
      identificationable_type: unknown
      issued_at: unknown
      notes: unknown
      number: unknown
      type: unknown
      updated_at: unknown
    }
  }
}
