// TypesFromSerializers CacheKey 3e5a92c694b16ddddaa19b0066c6be85
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsIndex {
      id: string
      created_at: Date
      expires_at?: Date
      extra_fields?: Record<string, string>
      id_type: "drivers_license" | "passport" | "state_id" | "military_id" | "employee_id" | "other"
      identificationable_id: string
      identificationable_type: string
      issued_at?: Date
      notes?: string
      number?: string
      updated_at: Date
    }
  }
}
