// TypesFromSerializers CacheKey 60d4870a2916622cae71a2fc6a338463
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsIndex {
      id: string
      created_at: string | Date
      expires_at?: string | Date
      extra_fields?: Record<string, string>
      identificationable_id: string
      identificationable_type: string
      issued_at?: string | Date
      notes?: string
      number?: number
      type?: number
      updated_at: string | Date
    }
  }
}
