// TypesFromSerializers CacheKey 294b8c80276df36b28ff01b589a403cc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsShow {
      id: string
      created_at: Date
      expires_at?: Date
      extra_fields?: Record<string, string>
      identificationable_id: string
      identificationable_type: string
      issued_at?: Date
      notes?: string
      number?: string
      type?: number
      updated_at: Date
    }
  }
}
