// TypesFromSerializers CacheKey 5c001e20981911e057513d16e37a757d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsShow {
      id: string
      created_at: Date
      expires_at?: Date
      extra_fields?: Record<string, string>
      identificationable_id: string
      identificationable_type: string
      issued_at?: Date
      notes?: string
      number?: string
      type: unknown
      updated_at: Date
    }
  }
}
