// TypesFromSerializers CacheKey a8a58d3789b7adc452e4ee67aaeccb74
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IdentificationsShow {
      id: unknown
      created_at: string | Date
      expires_at?: string | Date
      extra_fields?: Record<string, string>
      identificationable_id: unknown
      identificationable_type: string
      issued_at?: string | Date
      notes?: string
      number?: number
      type?: number
      updated_at: string | Date
    }
  }
}
