// TypesFromSerializers CacheKey 506b03ac62bb6d2b06610685806cda6c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RecurringPattern from '../RecurringPattern'
import type CalendarEventsShowSerializerSchedulable from './ShowSerializer/Schedulable'

declare global {
  namespace Schema {
    interface CalendarEventsShow {
      id: number
      created_at: string | Date
      created_by_id: number
      ends_at?: string | Date
      parent_id?: number
      recurring_pattern: RecurringPattern
      recurring_pattern_id?: number
      schedulable: CalendarEventsShowSerializerSchedulable
      schedulable_id?: number
      schedulable_type?: string
      starts_at?: string | Date
      updated_at: string | Date
    }
  }
}
