// TypesFromSerializers CacheKey 33ee528ac8c3ae9488c75880327db4c3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CalendarEventsShow {
      id: number
      created_at: string | Date
      created_by_id: number
      ends_at?: string | Date
      parent_id?: number
      recurring_pattern_id?: number
      schedulable_id?: number
      schedulable_type?: string
      starts_at?: string | Date
      updated_at: string | Date
    }
  }
}
