// TypesFromSerializers CacheKey d029e0a833545cfbf470de24aad5f29b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type RecurringPattern from '../RecurringPattern'

declare global {
  namespace Schema {
    interface CalendarEventsShow {
      id: number
      created_at: string | Date
      created_by_id: number
      ends_at?: string | Date
      parent_id?: number
      recurring_pattern: RecurringPattern
      recurring_pattern_id?: number
      schedulable_id?: number
      schedulable_type?: string
      starts_at?: string | Date
      updated_at: string | Date
    }
  }
}
