// TypesFromSerializers CacheKey 83f4620997fb7c7500f51a1cd1c84da9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsEdit {
      id: unknown
      created_at: string | Date
      first_name: unknown
      last_name: unknown
      notes: unknown
      updated_at: string | Date
    }
  }
}
