// TypesFromSerializers CacheKey 617afd4692bd11dcc195dfd84171a364
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsEdit {
      id: unknown
      slug?: unknown
      created_at: unknown
      first_name: unknown
      last_name: unknown
      notes: unknown
      updated_at: unknown
    }
  }
}
