// TypesFromSerializers CacheKey 98cbdacc1aa4a0ac3db2a15ed0e0d98f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsEdit {
      id: string
      slug?: string
      created_at: string | Date
      first_name: unknown
      last_name: unknown
      notes: unknown
      updated_at: string | Date
    }
  }
}
