// TypesFromSerializers CacheKey 3f02f061345c61b2c8c8632eb3fb6deb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsFormData {
      id?: unknown
      slug?: unknown
      first_name: unknown
      last_name: unknown
      notes: unknown
    }
  }
}
