// TypesFromSerializers CacheKey 4ce83477ec333c0b4308324cc81f8cdd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsFormData {
      id?: unknown
      first_name: unknown
      last_name: unknown
      notes: unknown
    }
  }
}
