// TypesFromSerializers CacheKey 4298c70eb36c09eecfe12e73fed4853a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsFormData {
      id?: string
      first_name: unknown
      last_name: unknown
      notes: unknown
    }
  }
}
