// TypesFromSerializers CacheKey e9573128c454780f5fa42eac7331aa68
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsIndex {
      id: string
      slug?: string
      created_at: Date
      first_name: string
      last_name: string
      name: string
      updated_at: Date
    }
  }
}
