// TypesFromSerializers CacheKey 1a8f7818d5403903d130d5f833faa42a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsIndex {
      id: string
      created_at: string | Date
      first_name: unknown
      last_name: unknown
      notes: unknown
      updated_at: string | Date
    }
  }
}
