// TypesFromSerializers CacheKey 3d828f27dc422fc9dec0280a604970f4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsIndex {
      id: string
      slug?: string
      created_at: string | Date
      first_name: unknown
      last_name: unknown
      notes: unknown
      updated_at: string | Date
    }
  }
}
