// TypesFromSerializers CacheKey a37e17cdf3bb0b32897615b64cd37315
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsOptions {
      id: string
      created_at: Date
      first_name: string
      full_name: string
      last_name: string
      name: string
      slug: string
      updated_at: Date
    }
  }
}
