// TypesFromSerializers CacheKey c0decca1c1c6fe0f3b99b02435937458
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsShow {
      id: number
      created_at: string | Date
      first_name?: string
      last_name?: string
      notes?: string
      updated_at: string | Date
    }
  }
}
