// TypesFromSerializers CacheKey 40d740afa9d2975bb542413b7f13be4f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DoctorsShow {
      id: string
      slug?: string
      created_at: Date
      first_name: unknown
      last_name: unknown
      notes: unknown
      updated_at: Date
    }
  }
}
