// TypesFromSerializers CacheKey 3d6f9c7c9cedd997f7e1d20d4e8b7004
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeoplePersisted from '../People/Persisted'

declare global {
  namespace Schema {
    interface DoctorsShow {
      id: string
      created_at: Date
      first_name: string
      full_name: string
      last_name: string
      name: string
      person: PeoplePersisted
      slug: string
      updated_at: Date
    }
  }
}
